### ISSUE TITLE
hfst-proc doesn't analyse words with / in them

### ISSUE THREAD

**Issue by hfst-importer** [hfst/hfst#104]
hfst-proc doesn't analyse words with / in them

To reproduce,

svn co https://apertium.svn.sourceforge.net/svnroot/apertium/staging/apertium-sme-nob
cd apertium-sme-nob
hfst-twolc -R -i apertium-sme-nob.sme.twol -o sme.twol.hfst
hfst-lexc -o sme.lexc.hfst apertium-sme-nob.sme.lexc
hfst-compose-intersect -1 sme.lexc.hfst -2 sme.twol.hfst -o nob-sme.autogen.hfst
hfst-invert -i nob-sme.autogen.hfst -o sme-nob.automorf.hfst
hfst-fst2fst -O -i sme-nob.automorf.hfst -o sme-nob.automorf.hfst.ol

sh autogen.sh
make sme-nob.automorf.hfst.ol

hfst-optimised-lookup does things correctly:

$ echo '24/12'|hfst-optimised-lookup sme-nob.automorf.hfst.ol 
24/12   24/12<Num><Sg><Acc>     0,000000
24/12   24/12<Num><Sg><Gen>     0,000000
24/12   24/12<Num><Sg><Nom>     0,000000

while hfst-proc tokenises on the /, which shouldn't happen if there is a longer analysis that includes the /:

$ echo '24\/12'| hfst-proc sme-nob.automorf.hfst.ol 
^24/24<Num><Sg><Acc>/24<Num><Sg><Gen>/24<Num><Sg><Nom>$\/^12/12<Num><Sg><Acc>/12<Num><Sg><Gen>/12<Num><Sg><Nom>$

Note: The input to hfst-proc is supposed to be escaped, typically this is done by putting a call to apertium-destxt/-deshtml/etc before hfst-proc.

Reported by: unhammer

**Comment by eaxelson** [comment]
Seems that hfst-proc now prints an error message if there are unescaped '/' characters.
