### ISSUE TITLE
unused variable in ol header spams warnings

### ISSUE THREAD

**Issue by hfst-importer** [hfst/hfst#131]
This warning comes randomly from files including hfst.hpp, makes debugging slightly harder:

/home/flammie/include/hfst/implementations/optimized-lookup/transducer.h: I global räckvidd:
/home/flammie/include/hfst/implementations/optimized-lookup/transducer.h|68 col 14| varoitus: ”hfst_ol::INFINITE_WEIGHT” är definierad men inte använd

Reported by: flammie

**Comment by eaxelson** [comment]
Seems that the variable is currently in use.
