### ISSUE TITLE
twolc prints everything to stderr

### ISSUE THREAD

**Issue by hfst-importer** [hfst/hfst#139]
It seems that twolc prints informational messages to stderr even when stdout is not reserved for automata output. This breaks things like silent-rules of automake:

  GEN    kal-phon.hfst
Reading input from kal-phon.twolc.
Writing output to kal-phon.hfst.
Reading alphabet.
Reading sets.
Reading and compiling definitions.
...

Should be just
  GEN     kal-phon.hfst
followed by only warnings and errors (in giellatekno svn langs/kal/).

Reported by: flammie

**Comment by eaxelson** [comment]
This has been fixed with new implementation of hfst-twolc that doesn't use pipelined scripts.
