### ISSUE TITLE
apertium-proc prints extra stuff on compounds of --cg

### ISSUE THREAD

**Issue by hfst-importer** [hfst/hfst#141]
$ echo a#b | hfst-strings2fst | hfst-fst2fst -f olw -o test.hfst
$ echo a#b | hfst-proc --cg test.hfst
"<a#b>"
        "a#b#b"

Expected:
"<a#b>"
        "a#b"

Reported by: flammie

**Comment by TinoDidriksen** [comment]
Closed by https://github.com/hfst/hfst/pull/465
