### ISSUE TITLE
hfst-twolc segfaults on simple grammar

### ISSUE THREAD

**Issue by hfst-importer** [hfst/hfst#188]
While testing space handling in twolc, following grammar made it segfault:

```
Alphabet
% A % A:0

;

Rules
"after A"
% A:0 <=> % A _ ;
```

Using:

```
$ hfst-twolc spacen-bug.twolc 
Reading input from spacen-bug.twolc.
Writing output to STDOUT.
Segmentation fault

syntax error, unexpected $end
on line 1:

Aborted.
```

Software versions from hfst.ling.helsinki.fi

Reported by: flammie

**Comment by eaxelson** [comment]
Seems that this has been fixed in the new implementation of hfst-twolc.
