### ISSUE TITLE
Flag diacritics break in hfst-lexc

### ISSUE THREAD

**Issue by hfst-importer** [hfst/hfst#213]
A flag in the attached lexicon breaks using hfst-lexc. This doe not happen in foma.

hfst-lexc 0.1 (hfst 3.6.1)
Copyright (C) 2010 University of Helsinki,
License GPLv3: GNU GPL version 3 http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ hfst-lexc mdf.foo.lexc > mdf.foo.hfst

$ hfst-lookup -X print-space -X show-flags mdf.foo.hfst 
hfst-lookup: warning: It is not possible to perform fast lookups with OpenFST, std arc, tropical semiring format automata.
Using HFST basic transducer format and performing slow lookups

> кандомс+V+TV+Ind+Prt1+ScSg2
> к а н д о м с +V +TV +Ind +Prt1 +ScSg2   к а н д      @P.CONJ.ObjAll@ > {ОЕØ} т ь @U.CONJ-MX.IND@ @U.CONJ-TX.PRT1@ @ U . C O N J - P X . 2 0 @  0.000000

Reported by: *anonymous

**Comment by eaxelson** [comment]
Seems that this has been fixed at some point. At least the minimal example works now.
