### ISSUE TITLE
Regexp2fst -S segfaults in syntax errors or missing ;

### ISSUE THREAD

**Issue by hfst-importer** [hfst/hfst#235]
On server so not much debug info:

    $ hfst-regexp2fst -S fixes-good.regex 
    Muistialueen ylitys (luotiin core-tiedosto)
    flammie@flammie ~/Koodit/giellatekno/startup-langs/gle/src (2249) [02:51:10] 
    $ gdb hfst-regexp2fst
    GNU gdb (Ubuntu 7.7-0ubuntu3.1) 7.7
    Copyright (C) 2014 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
    and     "show warranty" for details.
    This GDB was configured as "x86_64-linux-gnu".
    Type "show configuration" for configuration details.
    For bug reporting instructions, please see:
    <http://www.gnu.org/software/gdb/bugs/>.
    Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.
    For help, type "help".
    Type "apropos word" to search for commands related to "word"...
    Reading symbols from hfst-regexp2fst...done.
    (gdb) set args -S fixes-good.regex
    (gdb) run
    Starting program: /usr/local/bin/hfst-regexp2fst -S fixes-good.regex
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

    Program received signal SIGSEGV, Segmentation fault.
    __mempcpy_sse2 () at ../sysdeps/x86_64/memcpy.S:272
    272	../sysdeps/x86_64/memcpy.S: Tiedostoa tai hakemistoa ei ole.
    (gdb) bt
    #0  __mempcpy_sse2 () at ../sysdeps/x86_64/memcpy.S:272
    #1  0x00007ffff50a2589 in __GI__IO_default_xsputn (f=0x7fffffffcc20, 
    data=<optimized out>, n=13525) at genops.c:463
    #2  0x00007ffff5071c75 in _IO_vfprintf_internal (s=s@entry=0x7fffffffcc20, 
    format=<optimized out>, 
    format@entry=0x7ffff62e98b8 "***    parsing %60s [near %s]...\n", 
    ap=ap@entry=0x7fffffffcd58) at vfprintf.c:1661
    #3  0x00007ffff512ff84 in ___vsprintf_chk (
    s=0x7fffffffcee0 "***    parsing ! corrections\n\n#", '!' <repeats 38 times>, "\n# add         micheil -> michíl, muineál -> muiníl\n# thittí -> \n\n[[{tonn} %+Noun %+Fem %+Gen %+Weak %+Pl %+DefArt]:{dtonn}\n\t\t|[{tonn} "..., flags=1, 
    slen=18446744073709551615, 
    format=0x7ffff62e98b8 "***    parsing %60s [near %s]...\n", 
    args=args@entry=0x7fffffffcd58) at vsprintf_chk.c:84
    #4  0x00007ffff512fedd in ___sprintf_chk (
    s=s@entry=0x7fffffffcee0 "***    parsing ! corrections\n\n#", '!' <repeats 38 times>, "\n# add micheil -> michíl, muineál -> muiníl\n# thittí -> \n\n[[{tonn} %+Noun %+Fem %+Gen %+Weak %+Pl %+DefArt]:{dtonn}\n\t\t|[{tonn} "..., 
    flags=flags@entry=1, slen=slen@entry=18446744073709551615, 
    format=format@entry=0x7ffff62e98b8 "***    parsing %60s [near %s]...\n")
    at sprintf_chk.c:31
    #5  0x00007ffff62297ca in sprintf (
    __fmt=0x7ffff62e98b8 "***    parsing %60s [near %s]...\n", 
    __s=0x7fffffffcee0 "***    parsing ! corrections\n\n#", '!' <repeats 38 times>, "\n# add micheil -> michíl, muineál -> muiníl\n# thittí -> \n\n[[{tonn} %+Noun %+Fem %+Gen %+Weak %+Pl %+DefArt]:{dtonn}\n\t\t|[{tonn} "...)
    at /usr/include/x86_64-linux-gnu/bits/stdio2.h:34
    #6  xreerror (scanner=0x616500, msg=<optimized out>) at xre_utils.cc:50
    #7  0x416665442b25206c in ?? ()
    #8  0x612d6e7b3a5d7472 in ?? ()
    #9  0x686361656e686269 in ?? ()
    #10 0x7b5b7c09090a7d61 in ?? ()
    (gdb) bt -10
    #940 0x2520646e49747361 in ?? ()
    #941 0x2b25205167654e2b in ?? ()
    #942 0x68747b3a5d6e654c in ?? ()
    #943 0x2021097d616c7261 in ?? ()
    #944 0x61747b5b7c09090a in ?? ()
    #945 0x207d686769616c72 in ?? ()
    #946     0x2520627265562b25 in ?? ()
    #947 0x502b25204954562b in ?? ()
    #948 0x2520646e49747361 in ?? ()
    #949 0x00654c2b2520512b in ?? ()

    $ cat fixes-good.regex 
    ! corrections
    
    #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    # add micheil -> michíl, muineál -> muiníl
    # thittí -> 
    
    [[{tonn} %+Noun %+Fem %+Gen %+Weak %+Pl %+DefArt]:{dtonn}
		|[{tonn} %+Noun %+Fem %+Gen %+Weak %+Pl]:{tonn}
		|[{crios} %+Noun %+Masc %+Com %+Pl %+DefArt]:{criosanna}
		|[{crios} %+Noun %+Masc %+Com %+Pl %+Len]:{chriosanna}
		|[{crios} %+Noun %+Masc %+Com %+Pl]:{criosanna}
		|[{crios} %+Noun %+Masc %+Gen %+Strong %+Pl %+DefArt]:{gcriosanna}
		|[{crios} %+Noun %+Masc %+Gen %+Strong %+Pl]:{criosanna}
		|[{crios} %+Noun %+Masc %+Voc %+Pl %+DefArt]:{chriosanna}
		|[{ceann} %+Noun %+Masc %+Voc %+Sg]:{cheann}
		|[{pobal} %+Noun %+Masc %+Voc %+Sg]:{phobal}
		|[{rún} %+Noun %+Masc %+Voc %+Sg]:{rún}
		|[{stór} %+Noun %+Masc %+Voc %+Sg]:{stór}
		|[{abhainn} %+Noun %+Fem %+Com %+Pl %+DefArt]:{haibhneacha}
		|[{abhainn} %+Noun %+Fem %+Com %+Pl]:{aibhneacha}
		|[{abhainn} %+Noun %+Fem %+Gen %+Strong %+Pl %+DefArt]:{n-aibhneacha}
		|[{abhainn} %+Noun %+Fem %+Gen %+Strong %+Pl]:{aibhneacha}
		|[{abhainn} %+Noun %+Fem %+Voc %+Pl %+DefArt]:{aibhneacha}
		|[{ubh} %+Noun %+Fem %+Com %+Pl %+DefArt]:{huibheacha}
		|[{ubh} %+Noun %+Fem %+Com %+Pl]:{uibheacha}
		|[{ubh} %+Noun %+Fem %+Gen %+Strong %+Pl %+DefArt]:{n-uibheacha}
		|[{ubh} %+Noun %+Fem %+Gen %+Strong %+Pl]:{uibheacha}
		|[{ubh} %+Noun %+Fem %+Voc %+Pl %+DefArt]:{uibheacha}
		|[{bráthair} %+Noun %+Masc %+Com %+Pl %+DefArt]:{bráithre}
		|[{bráthair} %+Noun %+Masc %+Com %+Pl %+Len]:{bhráithre}
		|[{bráthair} %+Noun %+Masc %+Com %+Pl]:{bráithre}
		|[{bráthair} %+Noun %+Masc %+Gen %+Strong %+Pl %+DefArt]:{mbráithre}
		|[{bráthair} %+Noun %+Masc %+Gen %+Strong %+Pl]:{bráithre}
		|[{bráthair} %+Noun %+Masc %+Voc %+Pl %+DefArt]:{bhráithre}
    #!!		|[{bliain} %+Noun %+Fem %+Com %+Num %+DefArt]:{bliana}
		|[{teanga} %+Noun %+Fem %+Com %+Pl %+DefArt]:{teangacha}
		|[{teanga} %+Noun %+Fem %+Com %+Pl %+Len]:{theangacha}
		|[{teanga} %+Noun %+Fem %+Com %+Pl]:{teangacha}
		|[{teanga} %+Noun %+Fem %+Gen %+Strong %+Pl %+DefArt]:{dteangacha}
		|[{teanga} %+Noun %+Fem %+Gen %+Strong %+Pl]:{teangacha}
		|[{teanga} %+Noun %+Fem %+Voc %+Pl %+DefArt]:{theangacha}
		|[{roinnt} %+Noun %+Fem %+Com %+Pl %+DefArt]:{rannta}
		|[{roinnt} %+Noun %+Fem %+Com %+Pl]:{rannta}
		|[{roinnt} %+Noun %+Fem %+Gen %+Strong %+Pl %+DefArt]:{rannta}
		|[{roinnt} %+Noun %+Fem %+Gen %+Strong %+Pl]:{rannta}
		|[{roinnt} %+Noun %+Fem %+Voc %+Pl %+DefArt]:{rannta}
		|[{toradh} %+Noun %+Masc %+Com %+Pl %+DefArt]:{torthaí}
		|[{toradh} %+Noun %+Masc %+Com %+Pl %+Len]:{thorthaí}
		|[{toradh} %+Noun %+Masc %+Com %+Pl]:{torthaí}
		|[{toradh} %+Noun %+Masc %+Gen %+Strong %+Pl %+DefArt]:{dtorthaí}
		|[{toradh} %+Noun %+Masc %+Gen %+Strong %+Pl]:{torthaí}
		|[{toradh} %+Noun %+Masc %+Voc %+Pl %+DefArt]:{thorthaí}
		|[{ainm} %+Noun %+Masc %+Com %+Pl %+DefArt]:{hainmneacha}
		|[{ainm} %+Noun %+Masc %+Com %+Pl]:{ainmneacha}
		|[{ainm} %+Noun %+Masc %+Gen %+Strong %+Pl %+DefArt]:{n-ainmneacha}
		|[{ainm} %+Noun %+Masc %+Gen %+Strong %+Pl]:{ainmneacha}
		|[{ainm} %+Noun %+Masc %+Voc %+Pl %+DefArt]:{ainmneacha}
		|[{croí} %+Noun %+Masc %+Com %+Pl %+DefArt]:{croíthe}
		|[{croí} %+Noun %+Masc %+Com %+Pl %+Len]:{chroíthe}
		|[{croí} %+Noun %+Masc %+Com %+Pl]:{croíthe}
		|[{croí} %+Noun %+Masc %+Gen %+Strong %+Pl %+DefArt]:{gcroíthe}
		|[{croí} %+Noun %+Masc %+Gen %+Strong %+Pl]:{croíthe}
		|[{croí} %+Noun %+Masc %+Voc %+Pl %+DefArt]:{chroíthe}
		|[{dlí} %+Noun %+Masc %+Com %+Pl %+DefArt]:{dlíthe}
		|[{dlí} %+Noun %+Masc %+Com %+Pl]:{dlíthe}
		|[{dlí} %+Noun %+Masc %+Gen %+Strong %+Pl %+DefArt]:{ndlíthe}
		|[{dlí} %+Noun %+Masc %+Gen %+Strong %+Pl]:{dlíthe}
		|[{dlí} %+Noun %+Masc %+Voc %+Pl %+DefArt]:{dhlíthe}
		|[{rí} %+Noun %+Masc %+Com %+Pl %+DefArt]:{ríthe}
		|[{rí} %+Noun %+Masc %+Com %+Pl]:{ríthe}
		|[{rí} %+Noun %+Masc %+Gen %+Strong %+Pl %+DefArt]:{ríthe}
		|[{rí} %+Noun %+Masc %+Gen %+Strong %+Pl]:{ríthe}
		|[{rí} %+Noun %+Masc %+Voc %+Pl %+DefArt]:{ríthe}
		|[{brí} %+Noun %+Fem %+Com %+Pl %+DefArt]:{bríonna}
		|[{brí} %+Noun %+Fem %+Com %+Pl %+Len]:{bhríonna}
		|[{brí} %+Noun %+Fem %+Com %+Pl]:{bríonna}
		|[{brí} %+Noun %+Fem %+Gen %+Strong %+Pl %+DefArt]:{mbríonna}
		|[{brí} %+Noun %+Fem %+Gen %+Strong %+Pl]:{bríonna}
		|[{brí} %+Noun %+Fem %+Voc %+Pl %+DefArt]:{bhríonna}
		|[{caoi} %+Noun %+Fem %+Com %+Pl %+DefArt]:{caíonna}
		|[{caoi} %+Noun %+Fem %+Com %+Pl %+Len]:{chaíonna}
		|[{caoi} %+Noun %+Fem %+Com %+Pl]:{caíonna}
		|[{caoi} %+Noun %+Fem %+Gen %+Strong %+Pl %+DefArt]:{gcaíonna}
		|[{caoi} %+Noun %+Fem %+Gen %+Strong %+Pl]:{caíonna}
		|[{caoi} %+Noun %+Fem %+Voc %+Pl %+DefArt]:{chaíonna}
		|[{gnó} %+Noun %+Masc %+Com %+Pl %+DefArt]:{gnóthaí}
		|[{gnó} %+Noun %+Masc %+Com %+Pl %+Len]:{ghnóthaí}
		|[{gnó} %+Noun %+Masc %+Com %+Pl]:{gnóthaí}
		|[{gnó} %+Noun %+Masc %+Com %+Pl %+Len]:{ghnóthaí}
		|[{gnó} %+Noun %+Masc %+Gen %+Strong %+Pl %+DefArt]:{ngnóthaí}
		|[{gnó} %+Noun %+Masc %+Gen %+Strong %+Pl]:{gnóthaí}
		|[{gnó} %+Noun %+Masc %+Voc %+Pl %+DefArt]:{ghnóthaí}
		|[{tráthnóna} %+Noun %+Masc %+Com %+Pl %+DefArt]:{tráthnónta}
		|[{tráthnóna} %+Noun %+Masc %+Com %+Pl %+Len]:{thráthnónta}
		|[{tráthnóna} %+Noun %+Masc %+Com %+Pl]:{tráthnónta}
		|[{tráthnóna} %+Noun %+Masc %+Gen %+Strong %+Pl %+DefArt]:{dtráthnónta}
		|[{tráthnóna} %+Noun %+Masc %+Gen %+Strong %+Pl]:{tráthnónta}
		|[{tráthnóna} %+Noun %+Masc %+Voc %+Pl %+DefArt]:{thráthnónta}
		|[{contae} %+Noun %+Masc %+Com %+Pl %+DefArt]:{contaetha}
		|[{contae} %+Noun %+Masc %+Com %+Pl %+Len]:{chontaetha}
		|[{contae} %+Noun %+Masc %+Com %+Pl]:{contaetha}
		|[{contae} %+Noun %+Masc %+Gen %+Strong %+Pl %+DefArt]:{gcontaetha}
		|[{contae} %+Noun %+Masc %+Gen %+Strong %+Pl]:{contaetha}
		|[{contae} %+Noun %+Masc %+Voc %+Pl %+DefArt]:{chontaetha}
		|[{cliabh} %+Noun %+Masc %+Com %+Pl %+DefArt]:{cléibh}
		|[{cliabh} %+Noun %+Masc %+Com %+Pl %+Len]:{chléibh}
		|[{cliabh} %+Noun %+Masc %+Com %+Pl]:{cléibh}
		|[{cliabh} %+Noun %+Masc %+Gen %+Sg %+DefArt]:{chléibh}
		|[{cliabh} %+Noun %+Masc %+Gen %+Sg]:{cléibh}
		|[{beithíoch} %+Noun %+Masc %+Com %+Pl %+DefArt]:{beithígh}
		|[{beithíoch} %+Noun %+Masc %+Com %+Pl %+Len]:{bheithígh}
		|[{beithíoch} %+Noun %+Masc %+Com %+Pl]:{beithígh}
		|[{beithíoch} %+Noun %+Masc %+Gen %+Sg %+DefArt]:{bheithígh}
		|[{beithíoch} %+Noun %+Masc %+Gen %+Sg]:{beithígh}
		|[{díbirt} %+Noun %+Fem %+Gen %+Sg %+DefArt]:{díbeartha}
		|[{díbirt} %+Noun %+Fem %+Gen %+Sg]:{díbeartha}
		|[{obair} %+Noun %+Fem %+Gen %+Sg]:{oibre}
		|[{obair} %+Noun %+Fem %+Gen %+Sg %+DefArt]:{hoibre}
		|[{cearc} %+Noun %+Fem %+Gen %+Sg]:{circe}
		|[{cearc} %+Noun %+Fem %+Gen %+Sg %+DefArt]:{circe}
		|[{cearc} %+Noun %+Fem %+Gen %+Sg %+Len]:{chirce}
		|[{cearc} %+Noun %+Fem %+Gen %+Sg %+Ecl]:{gcirce}
    #		|[{cuid} %+Noun %+Fem %+Com %+Pl]:{codanna}
    #		|[{cuid} %+Noun %+Fem %+Com %+Pl %+DefArt]:{codanna}
    #		|[{cuid} %+Noun %+Fem %+Com %+Pl %+Len]:{chodanna}
    #		|[{cuid} %+Noun %+Fem %+Gen %+Strong %+Pl]:{codanna}
    #		|[{cuid} %+Noun %+Fem %+Gen %+Strong %+Pl %+DefArt]:{gcodanna}
    #		|[{cuid} %+Noun %+Fem %+Voc %+Pl %+DefArt]:{chodanna}
		|[{fuil} %+Noun %+Fem %+Com %+Pl]:{fola}
		|[{fuil} %+Noun %+Fem %+Com %+Pl %+DefArt]:{fola}
		|[{fuil} %+Noun %+Fem %+Com %+Pl %+Len]:{fhola}
		|[{fuil} %+Noun %+Fem %+Gen %+Strong %+Pl]:{fola}
		|[{fuil} %+Noun %+Fem %+Gen %+Strong %+Pl %+DefArt]:{bhfola}
		|[{fuil} %+Noun %+Fem %+Voc %+Pl %+DefArt]:{fhola}
		|[{draíocht} %+Noun %+Fem %+Com %+Pl]:{draíochta}
		|[{draíocht} %+Noun %+Fem %+Com %+Pl %+DefArt]:{draíochta}
		|[{draíocht} %+Noun %+Fem %+Com %+Pl %+Len]:{dhraíochta}
		|[{draíocht} %+Noun %+Fem %+Gen %+Strong %+Pl]:{draíochta}
		|[{draíocht} %+Noun %+Fem %+Gen %+Strong %+Pl %+DefArt]:{ndraíochta}
		|[{draíocht} %+Noun %+Fem %+Voc %+Pl %+DefArt]:{dhraíochta}
		|[{gabháil} %+Noun %+Fem %+Com %+Pl]:{gabhálacha}
		|[{gabháil} %+Noun %+Fem %+Com %+Pl %+DefArt]:{gabhálacha}
		|[{gabháil} %+Noun %+Fem %+Com %+Pl %+Len]:{ghabhálacha}
		|[{gabháil} %+Noun %+Fem %+Gen %+Strong %+Pl]:{gabhálacha}
		|[{gabháil} %+Noun %+Fem %+Gen %+Strong %+Pl %+DefArt]:{ngabhálacha}
		|[{gabháil} %+Noun %+Fem %+Voc %+Pl %+DefArt]:{ghabhálacha}
		|[{tarlaigh} %+Verb %+VTI %+PastInd %+Len]:{tharla}	! tharla not tharlaigh
		|[{tarlaigh} %+Verb %+VTI %+PastInd %+Neg %+Len]:{tharla}	! 
		|[{tarlaigh} %+Verb %+VTI %+PastInd %+NegQ %+Len]:{tharla}	! 
		|[{tarlaigh} %+Verb %+VTI %+PastInd %+Q %+Len]:{tharla}
		|[{feithicil} %+Noun %+Fem %+Com %+Sg]:{feithicil}
		|[{feithicil} %+Noun %+Fem %+Com %+Sg %+Len]:{fheithicil}
		|[{feithicil} %+Noun %+Fem %+Com %+Sg %+Ecl]:{bhfeithicil}
    #		|[{fidil} %+Noun %+Fem %+Com %+Sg]:{fidil}
    #		|[{fidil} %+Noun %+Fem %+Com %+Sg %+Len]:{fhidil}
    #		|[{fidil} %+Noun %+Fem %+Com %+Sg %+Ecl]:{bhfidil}
		|[{caibidil} %+Noun %+Fem %+Com %+Sg]:{caibidil}
		|[{caibidil} %+Noun %+Fem %+Com %+Sg %+Len]:{chaibidil}
		|[{caibidil} %+Noun %+Fem %+Com %+Sg %+Ecl]:{gcaibidil}
    #		|[{paidir} %+Noun %+Fem %+Com %+Sg]:{paidir}
    #		|[{paidir} %+Noun %+Fem %+Com %+Sg %+Len]:{phaidir}
    #		|[{paidir} %+Noun %+Fem %+Com %+Sg %+Ecl]:{bpaidir}
		|[{treighid} %+Noun %+Fem %+Com %+Sg]:{treighid}
		|[{treighid} %+Noun %+Fem %+Com %+Sg %+Len]:{threighid}
		|[{treighid} %+Noun %+Fem %+Com %+Sg %+Ecl]:{dtreighid}
    #		|[{faighin} %+Noun %+Fem %+Com %+Sg]:{faighin}
    #		|[{faighin} %+Noun %+Fem %+Com %+Sg %+Len]:{fhaighin}
    #		|[{faighin} %+Noun %+Fem %+Com %+Sg %+Ecl]:{bhfaighin}
		|[{saighean} %+Noun %+Fem %+Com %+Sg]:{saighean}
		|[{saighean} %+Noun %+Fem %+Com %+Sg %+Len]:{shaighean}
		|[{saighean} %+Noun %+Fem %+Com %+Sg]:{tsaighean}
    #		|[{daighear} %+Noun %+Fem %+Com %+Sg]:{daighear}
    #		|[{daighear} %+Noun %+Fem %+Com %+Sg %+Len]:{dhaighear}
    #		|[{daighear} %+Noun %+Fem %+Com %+Sg %+Ecl]:{ndaighear}
    #		|[{ladhar} %+Noun %+Fem %+Com %+Sg]:{ladhar}
		|[{meadar} %+Noun %+Fem %+Gen %+Sg]:{meidre}
		|[{meadar} %+Noun %+Fem %+Gen %+Sg %+Len]:{mheidre}
		|[{meadar} %+Noun %+Fem %+Gen %+Sg %+Ecl]:{meidre}
    #		|[{sceimheal} %+Noun %+Fem %+Com %+Sg]:{sceimheal}
    #		|[{sceimheal} %+Noun %+Fem %+Com %+Sg]:{tsceimheal}
		|[{traimil} %+Noun %+Fem %+Com %+Sg]:{traimil}
		|[{traimil} %+Noun %+Fem %+Com %+Sg %+Len]:{thraimil}
		|[{traimil} %+Noun %+Fem %+Com %+Sg %+Ecl]:{dtraimil}
		|[{inis} %+Noun %+Fem %+Com %+Sg]:{inis}
		|[{leithinis} %+Noun %+Fem %+Com %+Sg]:{leithinis}
		|[{caingean} %+Noun %+Fem %+Com %+Sg]:{caingean}
		|[{caingean} %+Noun %+Fem %+Com %+Sg %+Len]:{chaingean}
		|[{caingean} %+Noun %+Fem %+Com %+Sg %+Ecl]:{gcaingean}
		|[{trilis} %+Noun %+Fem %+Com %+Sg]:{trilis}
		|[{trilis} %+Noun %+Fem %+Com %+Sg %+Len]:{thrilis}
		|[{trilis} %+Noun %+Fem %+Com %+Sg %+Ecl]:{dtrilis}
		|[{geimheal} %+Noun %+Fem %+Com %+Sg]:{geimheal}
		|[{geimheal} %+Noun %+Fem %+Com %+Sg %+Len]:{gheimheal}
		|[{geimheal} %+Noun %+Fem %+Com %+Sg %+Ecl]:{ngeimheal}
		|[{aolchoinneal} %+Noun %+Fem %+Com %+Sg]:{aolchoinneal}
		|[{aolchoinneal} %+Noun %+Fem %+Com %+Sg %+hPref]:{haolchoinneal}
		|[{coinneal} %+Noun %+Fem %+Com %+Sg]:{coinneal}
		|[{coinneal} %+Noun %+Fem %+Com %+Sg %+Len]:{choinneal}
		|[{coinneal} %+Noun %+Fem %+Com %+Sg %+Ecl]:{gcoinneal}
		|[{ceolfhoireann} %+Noun %+Fem %+Com %+Sg]:{ceolfhoireann}
		|[{ceolfhoireann} %+Noun %+Fem %+Com %+Sg %+Len]:{cheolfhoireann}
		|[{ceolfhoireann} %+Noun %+Fem %+Com %+Sg %+Ecl]:{gceolfhoireann}
    #		|[{meitheal} %+Noun %+Fem %+Com %+Sg]:{meitheal}
    #		|[{meitheal} %+Noun %+Fem %+Com %+Sg %+Len]:{mheitheal}
		|[{aibítir} %+Noun %+Fem %+Com %+Sg]:{aibítir}
		|[{sluasaid} %+Noun %+Fem %+Com %+Sg]:{sluasaid}
		|[{sluasaid} %+Noun %+Fem %+Com %+Sg]:{tsluasaid}
		|[{dabhach} %+Noun %+Fem %+Com %+Sg]:{dabhach}
		|[{dabhach} %+Noun %+Fem %+Com %+Sg %+Len]:{dhabhach}
		|[{dabhach} %+Noun %+Fem %+Com %+Sg %+Ecl]:{ndabhach}
		|[{fothair} %+Noun %+Fem %+Com %+Pl %+DefArt]:{foithreacha}
		|[{fothair} %+Noun %+Fem %+Com %+Pl %+Len]:{fhoithreacha}
		|[{fothair} %+Noun %+Fem %+Com %+Pl %+Ecl]:{bhfoithreacha}
		|[{fothair} %+Noun %+Fem %+Gen %+Strong %+Pl]:{foithreacha}
		|[{fothair} %+Noun %+Fem %+Gen %+Strong %+Pl %+Len]:{fhoithreacha}
		|[{fothair} %+Noun %+Fem %+Gen %+Strong %+Pl %+DefArt]:{bhfoithreacha}
		|[{fothair} %+Noun %+Fem %+Gen %+Strong %+Pl %+Ecl]:{bhfoithreacha}
		|[{fothair} %+Noun %+Fem %+Voc %+Pl %+Len]:{fhoithreacha}
		|[{seamair} %+Noun %+Fem %+Com %+Sg]:{seamair}
		|[{seamair} %+Noun %+Fem %+Com %+Sg]:{tseamair}
		|[{domhain} %+Noun %+Fem %+Com %+Sg]:{domhain}
		|[{domhain} %+Noun %+Fem %+Com %+Sg %+Len]:{dhomhain}
		|[{domhain} %+Noun %+Fem %+Com %+Sg %+Ecl]:{ndomhain}
		|[{admháil} %+Noun %+Fem %+Com %+Sg]:{admháil}
		|[{admháil} %+Noun %+Fem %+Com %+Sg %+hPref]:{hadmháil}
		|[{éadáil} %+Noun %+Fem %+Com %+Sg]:{éadáil}
		|[{éadáil} %+Noun %+Fem %+Com %+Sg %+hPref]:{héadáil}
		|[{bréifin} %+Noun %+Fem %+Com %+Sg]:{bréifin}
		|[{bréifin} %+Noun %+Fem %+Com %+Sg %+Len]:{bhréifin}
		|[{bréifin} %+Noun %+Fem %+Com %+Sg %+Ecl]:{mbréifin}
    #		|[{crithir} %+Noun %+Fem %+Com %+Sg]:{crithir}
    #		|[{crithir} %+Noun %+Fem %+Com %+Sg %+Len]:{chrithir}
    #		|[{crithir} %+Noun %+Fem %+Com %+Sg %+Ecl]:{gcrithir}
		|[{mionn} %+Noun %+Masc %+Gen %+Weak %+Pl]:{mionn}
		|[{mionn} %+Noun %+Masc %+Gen %+Weak %+Pl %+DefArt]:{mionn}
		|[{furasta} %+Adj %+Comp]:{fusa}		! not furasta
		|[{furasta} %+Adj %+Comp %+Len]:{fhusa}	
		|[{fada} %+Adj %+Comp]:{faide} 			! not fada
		|[{fada} %+Adj %+Comp %+Len]:{fhaide}		
		|[{olc} %+Adj %+Comp]:{measa}			! not oilce
		|[{mór} %+Adj %+Comp]:{mó}			! not móire
		|[{olc} %+Adj %+Comp %+Len]:{mheasa}	

Reported by: flammie

**Comment by eaxelson** [comment]
Fixed in commit f296b6b.
