### ISSUE TITLE
Errors building HFST on OS X (and fixes)

### ISSUE THREAD

**Issue by hfst-importer** [hfst/hfst#237]
HFST revision 3976 doesn't build under OS X in these conditions:

```
export CC=clang CXX=clang++ "CXXFLAGS=-std=gnu++11 -stdlib=libc++"
./autogen.sh
./configure --enable-proc --with-foma --enable-lexc --enable-tagger --enable-calculate --enable-xfst --with-unicode-handler=ICU --enable-all-tools
./scripts/generate-cc-files.sh
```

Errors are http://codepad.org/fSgBQldl and attached diff is what I did to get around them.

Any use of tr1/unordered_map should be done in #ifdef checks for compiler/flags or otherwise detected in config.h, since TR1 is quickly being phased out in favour of C++11. The other changes are portable.

Building with clang++ also reveals a lot of dangerous warnings, such as using == when you meant = for setting a buffer's null terminator.

Reported by: TinoDidriksen

**Comment by eaxelson** [comment]
Closing this issue since there is now a working solution for using unordered containers in different environments.
