### ISSUE TITLE
Migrate HFST project to GitHub

### ISSUE THREAD

**Issue by hfst-importer** [hfst/hfst#280]
GitHub is currently the most popular source code repository for open-source projects. One of the best features is that it allows external contributors to develop changes, submit them for inclusion in the upstream project. It also allows upstream project committers to easily review and merge contributed code into the mainline project. Even though the number of contributors is quite small, I think hosting the code in GH would lower the barrier to entry for new contributions.

There's also been reliability issues with Sourceforge during the recent months.

For these reasons I propose that HFST project migrates to GitHub.

I've evaluated migrating the SVN code base to GitHub using two methods:
* svn2git (https://github.com/nirvdrum/svn2git) and
* GitHub import tool

The GitHub import tool is very easy to use and seems to be doing a good job, so that is the recommended method. Please test this to verify that all the needed information gets migrated (e.g. commits, tags, branches). A demo repository import can be found here:

https://github.com/hfst/hfst-import-test4

I've created a 'hfst' organization in Github and I'll hand over admin permissions to the HFST project committers, if you decide to move forward with the migration.

Reported by: *anonymous

**Comment by TinoDidriksen** [comment]
Done on 2016-03-03 by Erik Axelson.
