### ISSUE TITLE
hfst-fst2fst should warn if given both -w and -O

### ISSUE THREAD

**Issue by hfst-importer** [hfst/hfst#282]
I thought -w was weighted and -O was optimised, so I tried

    $ hfst-fst2fst -w -O -i sme.automorf.hfst  -o foo.hfst
    
but got an optimised *unweighted* hfst out, since -O means "optimised *unweighted*", not just "optimised". 

Maybe there should be a warning if the user passes conflicting arguments, instead of silently overriding previous arguments.

Reported by: unhammer

**Comment by eaxelson** [comment]
Fixed in commit 94b7607.
