### ISSUE TITLE
hfst-proc is missing or broken for new installations

### ISSUE THREAD

**Issue by hfst-importer** [hfst/hfst#295]
From omorfi bug report 14 https://github.com/flammie/omorfi/issues/14:

> not sure if related, but for some reason hfst-installation created hfst-proc as a link to a non-existant file. However, then just replaced that link with real 'hfst-proc' from the precompiled binaries.
> 
> Before that change, the omorfi configuration stopped to this:

```
checking for /work/bin/hfst_v383/bin/hfst-split... yes
checking for /work/bin/hfst_v383/bin/hfst-conjunct... yes
checking for /work/bin/hfst_v383/bin/hfst-proc... no
configure: error: HFST commandline tools are needed in /work/bin/hfst_v383/bin
ls -la /work/bin/hfst_v383/bin/hfst-proc
/work/bin/hfst_v383/bin/hfst-proc -> hfst-apertium-proc
ls -la /work/bin/hfst_v383/bin/hfst-apertium-proc
ls: cannot access /work/bin/hfst_v383/bin/hfst-apertium-proc: No such file or directory
```

> and the precompiled version is, which now exists in the hfst-directory

```
./hfst-proc --version
hfst-proc 0.0 (hfst 3.8.2)
```

Reported by: flammie

**Comment by eaxelson** [comment]
Fixed in commit cc258f5.
