### ISSUE TITLE
r4485 broke hyperminimisation builds

### ISSUE THREAD

**Issue by hfst-importer** [hfst/hfst#296]
r4485 broke the build of https://victorio.uit.no/langtech/trunk/langs/kal/ when configured with --with-hfst --without-xfst --enable-hyperminimisation

When running make in src/morphology/ :
- r4484 takes a minute and 1.1 GB RAM to compile lexicon.hfst
- r4485 never completes and eventually grows to use all available RAM (in my case 32 GB + 32 GB swap)

Without hyperminimisation, r4485 completes in 1m45s taking 1.8 GB RAM.

Reported by: TinoDidriksen

**Comment by eaxelson** [comment]
This has been fixed.
