### ISSUE TITLE
hfst-proc --weight-classes fix borked --xerox output

### ISSUE THREAD

**Issue by hfst-importer** [hfst/hfst#301]
meriponi_ for example the english morphology yields for input 'Every':
    meriponi_ Every   Every[ART]
    meriponi_ Every
    meriponi_ Every   Every[ADJ]+ADJ
    meriponi_ Every
    meriponi_ Every   Eve[N]+ERY[N/N]+N
    meriponi_ Every
    meriponi_ Every   Ev[N]+ERY[N/N]+N
    meriponi_ Every                                                         
    
    meriponi_ earlier it was:
    meriponi_ Every
    meriponi_ Every
    meriponi_ Every   Ev[N]+ERY[N/N]+N
    meriponi_ Every   Eve[N]+ERY[N/N]+N
    meriponi_ Every   Every[ADJ]+ADJ

    meriponi_ spectre: the changes from revision 4426 to 4427 in files
              tools/src/hfst-proc/formatter.cc and formatter.h changed the
              behaviour of hfst-proc

Reported by: unhammer

**Comment by eaxelson** [comment]
This seems to work now, so closing the issue.
