### ISSUE TITLE
Odd results 

### ISSUE THREAD

**Issue by koskenni** [hfst/hfst#311]
I am trying to work real problems with HFST Python interface on CSC taito-shell. Below is an extracted minimal test where I am surprised by the number of arcs in the 'pbf2afe' transducer which ought to be 3:

```
import libhfst
def copy(fst):
    return libhfst.HfstTransducer(fst)
def narcs(name, fst):
    print('{} arcs in {}'.format(fst.number_of_arcs(), name))
afe2pbf = libhfst.regex('äa->a')
narcs('afe2pbf', afe2pbf)
pbf2afe = copy(afe2pbf).invert()
narcs('pbf2afe', pbf2afe)

$ python3 test.py
3 arcs in afe2pbf
1385030 arcs in pbf2afe
$

$ hfst-compose -V
hfst-compose 0.1 (hfst 3.9.0)
```

**Comment by eaxelson** [comment]
SWIG has issues with functions returning self-references, so all transducer functions that return a reference to the transducer itself on the C++ side now return None on the Python side. This means that chaining functions is no more possible, so `pbf2afe = copy(afe2pbf).invert()` must be rewritten as `pbf2afe = copy(afe2pbf);
pbf2afe.invert()`
