### ISSUE TITLE
Flag elimination fails whenever there are more than one type of flags in a transducer

### ISSUE THREAD

**Issue by mpsilfve** [hfst/hfst#315]
Two examples. The first one has only one type of flags and it works:

<verbatim>
$ hfst-fst2txt /tmp/baz.hfst 
0    1    a    a    0.000000
1    2    @P.FOO.ON@    @P.FOO.ON@    0.000000
2    3    @D.FOO.ON@    @D.FOO.ON@    0.000000
3    0.000000
$ hfst-xfst
hfst[0]: read regex @"/tmp/baz.hfst"
? bytes. 4 states, 3 arcs, ? paths
hfst[1]: eliminate flags
hfst[1]: print net
Ss0:	(no arcs).
</verbatim>

The second one has two types of flags and it fails:

<verbatim>
$ hfst-fst2txt /tmp/quux.hfst 
0    1    a    a    0.000000
1    2    @P.FOO.ON@    @P.FOO.ON@    0.000000
2    3    @P.BAR.ON@    @P.BAR.ON@    0.000000
3    4    @D.FOO.ON@    @D.FOO.ON@    0.000000
4    0.000000

$ hfst-xfst
hfst[0]: read regex @"/tmp/quux.hfst"
? bytes. 5 states, 4 arcs, ? paths
hfst[1]: eliminate flags
hfst[1]: print net
Ss0:	a -> fs1.
fs1:	(no arcs).
</verbatim>

**Comment by eaxelson** [comment]
Fixed in git commit 76e9069.
