### ISSUE TITLE
Build fails on RHEL 6.7 with "invalid conversion from 'int' to 'const fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > >"

### ISSUE THREAD

**Issue by miljin** [hfst/hfst#324]
Hello

I am trying to compile HFST 3.10.0 (also tried 3.9.1, 3.9.0, same error) using the following commands:

./configure --enable-tagger --enable-calculate --enable-xfst --with-unicode-handler --enable-proc --enable-lexc --enable-lexc-wrapper
make

Somewhere in the middle of the process it gives me this:

/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_pair.h: In constructor 'std::pair<_T1, _T2>::pair(_U1&&, _U2&&) [with _U1 = int, _U2 = int, _T1 = int, _T2 = const fst::Fstfst::ArcTpl<fst::TropicalWeightTpl<float > >_]':
../../../back-ends/openfst/src/include/fst/rational.h:71:   instantiated from 'fst::RationalFstImpl<A>::RationalFstImpl(const fst::RationalFstOptions&) [with A = fst::ArcTplfst::TropicalWeightTpl<float >]'
../../../back-ends/openfst/src/include/fst/rational.h:287:   instantiated from 'fst::RationalFst<A>::RationalFst() [with A = fst::ArcTplfst::TropicalWeightTpl<float >]'
../../../back-ends/openfst/src/include/fst/closure.h:109:   instantiated from 'fst::ClosureFst<A>::ClosureFst(const fst::Fst<A>&, fst::ClosureType) [with A = fst::ArcTplfst::TropicalWeightTpl<float >]'
TropicalWeightTransducer.cc:1832:   instantiated from here
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/stl_pair.h:90: error: invalid conversion from 'int' to 'const fst::Fstfst::ArcTpl<fst::TropicalWeightTpl<float > >_'
make[5]: **\* [TropicalWeightTransducer.lo] Error 1
make[5]: Leaving directory `/root/omorfi-install/hfst-3.10.0/libhfst/src/implementations'
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory`/root/omorfi-install/hfst-3.10.0/libhfst/src'
make[3]: **\* [all] Error 2
make[3]: Leaving directory `/root/omorfi-install/hfst-3.10.0/libhfst/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory`/root/omorfi-install/hfst-3.10.0/libhfst'
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory `/root/omorfi-install/hfst-3.10.0'
make: **\* [all] Error 2

Build completes successfully only with hfst 3.8.3. What could be done about the newer versions?

**Comment by flammie** [comment]
is RPM by @TinoDidriksen in http://wiki.apertium.org/wiki/Installation possible on RHEL?

**Comment by TinoDidriksen** [comment]
RHEL/CentOS 6 support was officially dropped a while ago, so the nightly build doesn't try for it either.
