### ISSUE TITLE
hfst-pmatch2fst treats path relative to invocation CWD instead of script's directory

### ISSUE THREAD

**Issue by flammie** [hfst/hfst#325]
I tried making an pmatch tokeniser in omorfi by

```
mkdir src/tokeniser
cat > src/tokeniser/omorfi-tokenise.pmatch
define dictword @"../generated/omorfi.accept.hfst";
define token LC(Whitespace | Punct | #) [dictword | Punct] RC(Whitespace | Punct | #) ;
define TOP token;
hfst-pmatch2fst src/tokeniser/omorfi-tokenise.pmatch -o src/generated/omorfi.tokenise.pmatchfst
*** pmatch parsing failed: Couldn't read transducer from ../generated/omorfi.accept.hfst
*** parsing  [line 1, near @"../generated/omorfi.accept.hfst"]
```

If I use path `src/generated/omorfi.accept.hfst` it works, but of course this would break if I am compiling from different directory which is quite unusual behaviour for a compiler.

**Comment by Traubert** [comment]
As far as I can see, the standard portable C++ (in our case, both Windows and unix) path solution will only be available in C++17, now in experimental/filesystem. It's more or less a merge from boost's implementation. Unfortunately we can't use that yet.

For now, what we could do is to

1) Only support script-relative pathnames in unix
2) Use filename[0] == '/' to determine whether a @ path is absolute. If it is, use it.
3) If it isn't, use realpath( dirname(script's directory) + relative pathname) to get the filename

Does that sound reasonable?

**Comment by flammie** [comment]
mmh, that makes sense, for my use it would be enough to only have relative paths work in unix and print informative message on windows, or always advice user to use absolute paths, or ask for a inclusion path via option or environment variables, roughly in that order. Using
 path relative to callers working directory is probably the most confusing option, given that it leads to syntax error whether the compiler is called from this or that directory.

**Comment by Traubert** [comment]
Finally resolved - for unix users only so far, unfortunately.
