### ISSUE TITLE
warn on undefined multichar symbols within < > in lexc?

### ISSUE THREAD

**Issue by unhammer** [hfst/hfst#331]
running

```
Multichar_Symbols
+Acr

LEXICON Root
< {etc} "+Arc":0 > # ;
```
through hfst-lexc --verbose does not mention that  the typo "+Arc" is not in the lexc's multichar symbols, it would be nice if we could have a warning.

(Even nicer would be warnings on things like `etc:+Arc`, but I have no idea if that would be possible.)

**Comment by flammie** [comment]
For pair strings the best heuristic in HFST 2 was perhaps to check for matching brackets, maybe on analysis side only without matching part on other level... it still lead to some false warnings and lots of unreadable code, an upgrade away from Xerox's formats would be a better long term solution.

**Comment by eaxelson** [comment]
Now user is warned about undefined symbols when compiling lexc in verbose mode (commit d0a1b55).
