### ISSUE TITLE
hfst-fst2txt generates invalid .dot file

### ISSUE THREAD

**Issue by DavidNemeskey** [hfst/hfst#339]
The title is too harsh, but _hfst-fst2txt_ does generate a .dot file with syntax errors if one end of the transduction is a `"` (double quote) character. Such a rule results in a line like

```
q100 -> q101 [label="":X "];
```

, even though the `"` should be escaped, like so:

```
q100 -> q101 [label="\":X "];
```

**Comment by eaxelson** [comment]
Seems this issue has been fixed.
