### ISSUE TITLE
AttributeError: module '_libhfst' has no attribute 'SFST_TYPE'

### ISSUE THREAD

**Issue by ljleppan** [hfst/hfst#344]
## 1. Summary
Importing `hfst` or `libhfst` causes a `AttributeError: module '_libhfst' has no attribute 'SFST_TYPE'`after installing through pip in a python 3.5 virtual environment.

### 1.1 Software version information
HFST: `hfst-3.12.1.1b0`
Python: `Python 3.5.2 (default, Nov 17 2016, 17:05:23)`
GCC: `GCC 5.4.0 20160609` 
pip: `pip 9.0.1 from /home/ljleppan/venv/lib/python3.5/site-packages (python 3.5)`

### 1.2 OS & Version
```
ljleppan@hp8x-52:~$ lsb_release -a
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:printing-9.20160110ubuntu0.2-amd64:printing-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

```

## 2. Steps to reproduce
1) Activate virtual environment
2) Install hfst using `pip install hfst`
3) Run `python -c "import hfst"`

## 3. Expected result
Module imported successfully.

## 4. Actual result
Module import fails with following error:
```
(venv) ljleppan@hp8x-52:~$ python -c "import hfst"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ljleppan/venv/lib/python3.5/site-packages/hfst/__init__.py", line 52, in <module>
    import hfst.exceptions
  File "/home/ljleppan/venv/lib/python3.5/site-packages/hfst/exceptions/__init__.py", line 38, in <module>
    from libhfst import HfstException,\
  File "/home/ljleppan/venv/lib/python3.5/site-packages/libhfst.py", line 1426, in <module>
    SFST_TYPE = _libhfst.SFST_TYPE
AttributeError: module '_libhfst' has no attribute 'SFST_TYPE'
```

## 5. Other information
Using some debug prints in `libhfst.py` reveals that when called, `swig_import_helper()` succeeds in both calling `imp.find_module(...)` and in calling `imp.load_module(...)`: and `import _libhfst` is *not* called.

The error is caused by calling `_libhfst.SFST_TYPE`, where `_libhfst` is the module loaded by `swig_import_helper()`. Observing the contents of `_libhfst`, it seems while it does not have the required field `SFST_TYPE`, it does instead have a field called `SFST_TYPE_swigconstant`. I do not understand enough about Swig to determine what is going on in more detail, but I'm guessing that is some type of Swig configuration issue?

I can provide a verbose log of the pip install if that is in any way helpful.

**Comment by eaxelson** [comment]
For ubuntu, we recommend using debian packages (available at http://apertium.projectjj.com/apt/nightly/pool/main/h/hfst/). Documentation about the installation can be found at https://kitwiki.csc.fi/twiki/bin/view/KitWiki/HfstPython.
