### ISSUE TITLE
twol parsing issue

### ISSUE THREAD

**Issue by jonorthwash** [hfst/hfst#355]
I'm having a weird issue with twol syntax.  It seems to be related to syntax surrounding `.#.`, but might be related to to `/` or `:0` or some combination of these things.

Here's my **input files**.

`apertium-abc.abc.lexc`:

```
Multichar_Symbols

%<n%>   ! Noun
%<sg%>  ! Singular
%{A%}   ! Random archiphoneme
%>      ! Morpheme boundary

LEXICON Root

NounRoot ;

LEXICON RegNounInfl

%<n%>%<sg%>: # ;

LEXICON NounRoot

bibaBbbé¹:biba%{A%}%>b%>bé RegNounInfl ;
bibaBbbé²:biba%{A%}bbé RegNounInfl ;
biAbabbé¹:bi%{A%}ba%>b%>bé RegNounInfl ;
biAbabbé²:bi%{A%}babbé RegNounInfl ;
```

`apertium-abc.abc.twol`:
```
Alphabet
 A B Ç D E É Ä F G H I J Ž K L M N Ň O Ö P R S Ş T U Ü W Y Z
 a b ç d e é ä f g h i j ž k l m n ň o ö p r s ş t u ü w y z
 %{A%}:a %>:0  ;

Sets

Vow = A E É Ä I O Ö U Ü Y
      a e é ä i o ö u ü y ;

Cns = B Ç D F G H J Ž K L M N Ň P R S Ş T W Z
      b ç d f g h j ž k l m n ň p r s ş t w z ;

Rules 

"change {A} to b when in penultimate open syllable"
%{A%}:b <=> _ [ :Cns+ :Vow+ ]/:0* .#. ;
!%{A%}:b <=> _ [ :Cns+ :Vow+ ]/>:* .#. ;
```

I **compile them** the standard apertium way (potentially something missing here):
```
hfst-twolc apertium-abc.abc.twol -o .deps/abc.twol.hfst
cat apertium-abc.abc.lexc | grep -v 'Dir/RL' > .deps/abc.LR.lexc
hfst-lexc .deps/abc.LR.lexc -o .deps/abc.LR.lexc.hfst -v
hfst-compose-intersect -1 .deps/abc.LR.lexc.hfst -2 .deps/abc.twol.hfst -o .deps/abc.LR.hfst
hfst-invert .deps/abc.LR.hfst | hfst-fst2fst -O -o abc.automorf.hfst
hfst-fst2txt abc.automorf.hfst | gzip -9 -c -n > abc.automorf.att.gz
zcat < abc.automorf.att.gz > .deps/abc.automorf.att
lt-comp lr .deps/abc.automorf.att abc.automorf.bin
cat apertium-abc.abc.lexc | grep -v 'Dir/LR' > .deps/abc.RL.lexc
hfst-lexc .deps/abc.RL.lexc -o .deps/abc.RL.lexc.hfst -v
hfst-compose-intersect -1 .deps/abc.RL.lexc.hfst -2 .deps/abc.twol.hfst -o .deps/abc.RL.hfst
hfst-fst2fst -O .deps/abc.RL.hfst -o abc.autogen.hfst
hfst-fst2txt abc.autogen.hfst | gzip -9 -c -n > abc.autogen.att.gz
zcat < abc.autogen.att.gz > .deps/abc.autogen.att
lt-comp lr .deps/abc.autogen.att abc.autogen.bin
```

Here's the **output** of `hfst-expand .deps/abc.LR.lexc.hfst`:
```
biAbabbé¹<n><sg>:bi{A}ba>b>bé
biAbabbé²<n><sg>:bi{A}babbé
bibaBbbé¹<n><sg>:biba{A}>b>bé
bibaBbbé²<n><sg>:biba{A}bbé
```

Here's the **expected output** of `hfst-expand abc.automorf.hfst` (with either twol rule):
```
biababbé:biAbabbé¹<n><sg>
biababbé:biAbabbé²<n><sg>
bibabbbé:bibaBbbé¹<n><sg>
bibabbbé:bibaBbbé²<n><sg>
```

Here's the **actual output** of `hfst-expand abc.automorf.hfst` (with either twol rule):
```
bibbabbé:biAbabbé¹<n><sg>
bibbabbé:biAbabbé²<n><sg>
bibaabbé:bibaBbbé¹<n><sg>
bibabbbé:bibaBbbé²<n><sg>
```

Note that only the last of these comes out as expected; the other three are not as expected.  Also note that I tried with vowels that aren't `é` (like `i`), with similar results.

Some of the behaviour seems consistent with `.#.` being ignored (e.g., `bi{A}ba>b>bé:bibbabbé`), but that doesn't explain the differing behaviour of `bi{A}babbé:biababbé` or why the other two forms *don't* get the rule applied.

**Comment by jonorthwash** [comment]
Confirmed by @ftyers with a different test case:
```
fran@zarema:/tmp$ cat abc.lexc
Multichar_Symbols

%<n%>   ! Noun
%<sg%>  ! Singular
%{A%}   ! Random archiphoneme
%>      ! Morpheme boundary

LEXICON Root

NounRoot ;

LEXICON RegNounInfl

%<n%>%<sg%>: # ;

LEXICON NounRoot

ratatat:rata%{A%}t%>ta RegNounInfl ;
gabagab:gaba%{A%}tta RegNounInfl ;
snipsnap:sni%{A%}pa%>s%>na RegNounInfl ;
waccawac:wa%{A%}cawca RegNounInfl ;

fran@zarema:/tmp$ cat abc.twol
Alphabet
 A B Ç D E É Ä F G H I J Ž K L M N Ň O Ö P R S Ş T U Ü W Y Z
 a b ç d e é ä f g h i j ž k l m n ň o ö p r s ş t u ü w y z
 %{A%}:a %>:0  ;

Sets

Vow = A E É Ä I O Ö U Ü Y
      a e é ä i o ö u ü y ;

Cns = B Ç D F G H J Ž K L M N Ň P R S Ş T W Z
      b ç d f g h j ž k l m n ň p r s ş t w z ;

Rules 

"change {A} to b when in penultimate syllable"
%{A%}:ç <=> _  [ :Cns+ :Vow+ ]/:0*  .#. ;

!@ g:g a:a b:b a:a {A}:ç t:t t:t a:a 
!@ s:s n:n i:i {A}:a p:p a:a >:0 s:s >:0 n:n a:a

fran@zarema:/tmp$ cat Makefile 
all:
	hfst-lexc abc.lexc -o abc.lexc.hfst
	hfst-twolc abc.twol -o abc.twol.hfst
	hfst-compose-intersect -1 abc.lexc.hfst -2 abc.twol.hfst -o abc.hfst 
	hfst-fst2strings abc.lexc.hfst | sort > /tmp/a
	hfst-fst2strings abc.hfst | sort > /tmp/b
	paste /tmp/a /tmp/b

fran@zarema:/tmp$ make
hfst-lexc abc.lexc -o abc.lexc.hfst
hfst-lexc: warning: Defaulting to OpenFst tropical type
Root...1 RegNounInfl...1 NounRoot...
hfst-twolc abc.twol -o abc.twol.hfst
Reading input from abc.twol.
Writing output to abc.twol.hfst.
Reading alphabet.
Reading sets.
Reading rules and compiling their contexts and centers.
Compiling rules.
Storing rules.
hfst-compose-intersect -1 abc.lexc.hfst -2 abc.twol.hfst -o abc.hfst 
hfst-fst2strings abc.lexc.hfst | sort > /tmp/a
hfst-fst2strings abc.hfst | sort > /tmp/b
paste /tmp/a /tmp/b

gabagab<n><sg>:gaba{A}tta	gabagab<n><sg>:gabaçtta
ratatat<n><sg>:rata{A}t>ta	ratatat<n><sg>:rataatta
snipsnap<n><sg>:sni{A}pa>s>na	snipsnap<n><sg>:sniçpasna
waccawac<n><sg>:wa{A}cawca	waccawac<n><sg>:waacawca
```

**Comment by flammie** [comment]
I said this on IRC as well, but I kind of natively read that * at the end of []/X* scopes over whole bunch, since I thought / splices single arcs over [], but you should check hfst-fst2txt to see if it is so (debugging with hfst-fst2txt or hfst-fst2strings of twolc "ruleset" is easy if you have one rule only, since it's efficiently just a single automaton i.e. a rewrite rule then).

**Comment by mpsilfve** [comment]
I can take a look at this. Probably have time next week.

**Comment by jonorthwash** [comment]
In the past, the `*` in `/X*` has only applied to `X`.  Has that changed @flammie ?

**Comment by flammie** [comment]
No you are probably right, I was reading hfst2txt lazily, also since regexp2fst doesn't allow :0 as shorthand since it doesn't have the alphabet concept I guess. Nevertheless, debugging going through the ATT text of the rule might be revealing if you have time.

**Comment by mpsilfve** [comment]
Term complement is "\X" no "/X" as indicated in the documentation (https://kitwiki.csc.fi/twiki/bin/view/KitWiki/HfstTwolC?skin=clean.nat%2ceditdefault%2c%20pattern#Regular_Expression_Syntax). Does this fix your issue?

**Comment by jonorthwash** [comment]
Hm, I don't think the term-complement operator will help here.  I'm trying to use the ignore operator.

**Comment by mpsilfve** [comment]
I see. That one is not part of the hfst-twolc syntax. But maybe the term-complement could be used to do something similar?

**Comment by mpsilfve** [comment]
Okay! I understand now :) I'll fix it when as soon as I'll manage to locate the hfst-twolc bison files.

**Comment by mpsilfve** [comment]
Should be fixed in the most recent revision.

**Comment by mpsilfve** [comment]
Feel free to re-open, if this persists.

**Comment by jonorthwash** [comment]
I just tested today; it seems to be working.  Thanks!
