### ISSUE TITLE
hfst-xfst: set print-weight on|off has no effect

### ISSUE THREAD

**Issue by simon-clematide** [hfst/hfst#356]
Setting the global variable print-weight has no effect (tested on MACOS). Only the global command line switch -w works.
```
$ hfst-xfst -f openfst-tropical
hfst[0]: read regex a::1;
? bytes. 2 states, 1 arcs, ? paths
hfst[1]: down a
a
hfst[1]: set print-weight on
variable print-weight = on
hfst[1]: down a
a
```

**Comment by eaxelson** [comment]
Seems that the problem is that set doesn't recognize value 'on', it must be 'ON':

`set print-weight ON`

I guess 'on' should be accepted too, and a warning should be issued for values that are not recognized.

**Comment by simon-clematide** [comment]
Oh, right, I was used to xfst which does not care about true casing. Silent acceptance was really irritating for me.
