### ISSUE TITLE
ordering of "--no-weights" option affects out put in hfst-tokenise; option must come after --giella-cg

### ISSUE THREAD

**Issue by rueter** [hfst/hfst#371]
Sam, can you have a look at this?
the ordering:
hfst-tokenise --no-weights --giella-cg 
will not remove weights.
The ordering 
hfst-tokenise --giella-cg --no-weights
will remove them 
<eg>
:myv jackrueter$ echo "ансяк" | hfst-tokenise --no-weights --giella-cg tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst 
"<ансяк>"
	"ансяк" Adv Exclusive <W:0.0000000000>
:\n
"<>"
	"<" PUNCT LEFT <W:0.0000000000>
	">" PUNCT LEFT <W:0.0000000000>
	"«" PUNCT RIGHT <W:0.0000000000>
	"»" PUNCT RIGHT <W:0.0000000000>
</eg>
<eg>
1BQQ6GF:myv jackrueter$ echo "ансяк" | hfst-tokenise --giella-cg --no-weights tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst 
"<ансяк>"
	"ансяк" Adv Exclusive
:\n
"<>"
	"<" PUNCT LEFT
	">" PUNCT LEFT
	"«" PUNCT RIGHT
	"»" PUNCT RIGHT
</eg>

**Comment by TinoDidriksen** [comment]
Not a bug. `--help` says `-g` implies `-w -l2`, so it is natural to need `-W` after `-g`. It is normal that later options override earlier ones, and this is important behavior in scripts.
