### ISSUE TITLE
hfst-push-weights should warn on (or handle) optimised lookup automata

### ISSUE THREAD

**Issue by unhammer** [hfst/hfst#372]
```
$ diff -qs <(hfst-fst2txt errmodel.default.hfst)  <(hfst-fst2fst -f openfst-tropical  errmodel.default.hfst | hfst-push-weights --push=initial|hfst-fst2txt)
Files /dev/fd/63 and /dev/fd/62 differ
```
as expected, but if I leave the original fst in hfst-ol format:
```
$ diff -qs <(hfst-fst2txt errmodel.default.hfst)  <( <errmodel.default.hfst hfst-push-weights --push=initial|hfst-fst2txt)
Files /dev/fd/63 and /dev/fd/62 are identical
```
nothing is changed, and there is no warning

**Comment by eaxelson** [comment]
By default, the command line tools do not accept transducers in optimized lookup format. The transducers must first be converted to e.g. openfst-tropical format. This is now fixed in hfst-push-weights (commit b58f63e). It prints an error message if given a transdcucer in OL format.
