### ISSUE TITLE
hfst-proc tokenises badly when input-prefix includes space and is shared with possible analysis

### ISSUE THREAD

**Issue by jonorthwash** [hfst/hfst#380]
Correct and expected input/output:
```
echo бара ма | hfst-proc kaz.automorf.hfst 
^бара ма/бар<v><iv><aor><p3><pl>+ма<qst>/бар<v><iv><aor><p3><sg>+ма<qst>$

$ echo бара му | hfst-proc kaz.automorf.hfst 
^бара/бар<v><iv><gna_impf>/бар<v><iv><prc_impf>$ ^му/*му$

$ echo маған | hfst-proc kaz.automorf.hfst 
^маған/мен<prn><pers><p1><sg><dat>$
```

However, the following input results in the subsequent unexpected output:
```
$ echo бара маған | hfst-proc kaz.automorf.hfst 
^бара маған/*бара маған$
```

The expected output is
```
^бара/бар<v><iv><gna_impf>/бар<v><iv><prc_impf>$ ^маған/мен<prn><pers><p1><sg><dat>$
```

The generalisation seems to be that if the beginning of a string in ambiguous tokenisation cases can result in a single token, it will—even if (1) it results in no valid path and (2) a two-token analysis results in two known tokens.

**Comment by TinoDidriksen** [comment]
Closed by https://github.com/hfst/hfst/pull/465
