### ISSUE TITLE
Help Required

### ISSUE THREAD

**Issue by arghyatiger** [hfst/hfst#384]
Hello ,

@eaxelson  I am working on wrapping the transducer.cc model using swig. And was using your code as reference. I have a few doubts, so if you don't mind, is there any way i can contact you and get the doubts clarified 

Thanks in Advance
Arghya Bhattacharya

**Comment by eaxelson** [comment]
Hi,

you can for example use my university email (firstname.lastname@helsinki.fi).

br,
Erik Axelson

**Comment by arghyatiger** [comment]
@eaxelson I've sent an email, take a look at it when you have the time :D

Thanks
