### ISSUE TITLE
Passing -e "hyvästi" to hfst-xfst requires pressing enter

### ISSUE THREAD

**Issue by ftyers** [hfst/hfst#385]
The following hangs waiting for input:
```
$ hfst-xfst -e "source uig.guesser.hfst" -e "save stack .deps/guesser.hfst" -e "hyvästi"
 Defined
 'Vow'
Defined
 'Cns'
Defined
 'Syll'
Defined
 'Stem'
? bytes. 4 states, 120 arcs, ? paths
.
hfst[1]: 
```

This is fixed by:
```
$ echo "" | hfst-xfst -e "source uig.guesser.hfst" -e "save stack .deps/guesser.hfst" -e "hyvästi"
 Defined
 'Vow'
Defined
 'Cns'
Defined
 'Syll'
Defined
 'Stem'
? bytes. 4 states, 120 arcs, ? paths
.
hfst[1]: 
$
```

Is this intentional behaviour ? It would be cool to have an option to quit after running a series of commands.

**Comment by eaxelson** [comment]
I would say this is intentional as the -e option executes commands _on startup_

>   -e, --execute=CMD        Execute command CMD on startup

I now added option (commit 59e314d)

>  -E, --execute-and-quit=CMD Execute command CMD, and quit
