### ISSUE TITLE
missing files in source tarballs due to incorrect conditionals

### ISSUE THREAD

**Issue by arekm** [hfst/hfst#391]
There are many conditional variables used in Makefile.am files. The problem is that source files (at make dist) are packaged based on these conditionals. The end result is that if conditional is not enabled then some related source files do not end up in resulting tar.gz tarball.

Source tarball should *always* contain all source files regardless of build options used.

Example:

man/Makefile.am:

if WANT_TRAIN_TAGGER
  hfst_train_tagger=hfst-train-tagger.1
  hfst_train_tagger_subprograms=hfst-open-input-file-for-tagger.1 \
        hfst_tagger_compute_data_statistics.py.1 hfst-build-tagger.1 # hand-written
else
  hfst_train_tagger=
  hfst_train_tagger_subprograms=
endif

dist_man1_MANS=... $(hfst_train_tagger) ...

Now someone from hfst team creates new tarball and doesn't use --enable-train-tagger. Result - hfst-train-tagger.1 will not be put into resulting tarball. Any user of that tarball won't be able to use --enable-train-tagger.

So far found these files to be missing:
man/hfst-foma.1
man/hfst-foma-wrapper.1
man/hfst-lexc-wrapper.1
man/hfst-train-tagger.1
man/hfst-open-input-file-for-tagger.1
man/hfst_tagger_compute_data_statistics.py.1
man/hfst-build-tagger.1
tools/src/hfst-tagger/src/hfst-train-tagger.sh
tools/src/hfst-tagger/src/hfst-train-tagger.bat

**Comment by eaxelson** [comment]
Fixed in commit a7f2714.
