### ISSUE TITLE
hfst-twolc error messages

### ISSUE THREAD

**Issue by flammie** [hfst/hfst#394]
I might have broken something in my system, but currently when I'm trying hfst-twolc with one toy example and I get this:

```
$ cat test.twol

Alphabet
a b c o p q r s u ä ö ü

%{A%}:a
%{A%}:ä
%{O%}:o
%{O%}:ö
%{U%}:u
%{U%}:ü


Rules

"Dummy rule"
b:b <=> _ ;

$ hfst-twolc -i test.twol -o test.twol.hfst
Reading input from test.twol.
Writing output to test.twol.hfst.
Exception: HfstException in file: htwolcpre1-parser.yy on line: 541

```
I wonder if something's broken with the hfst installation I have here or if the lexer / parser error messages have gone missing in some recent change.

**Comment by eaxelson** [comment]
I also get the exception. I now fixed hfst-twolc so that errors and warnings are not suppressed:

> Reading input from issue-394.twol.
> Writing output to issue-394.twol.hfst.
> 
> syntax error, unexpected RULES_DECLARATION
> on line 12:
> "Dummy rule"
> Aborted.
> 
> Exception: HfstException in file: htwolcpre1-parser.yy on line: 541

**Comment by eaxelson** [comment]
I added a missing semicolon at the end of Alphabet declaration and that seems to fix it.

**Comment by flammie** [comment]
Exactly what I needed, thanks,
