### ISSUE TITLE
Wanted: hfst-realign

### ISSUE THREAD

**Issue by snomos** [hfst/hfst#400]
In many cases fst compilation and mangling back and forth results in sequences of symbol pairs like `A:0 0:A`. This gives a larger and slower fst than necessary, and more importantly, it creates [tokenisation issues](http://giellatekno.uit.no/bugzilla/show_bug.cgi?id=2468) for `hfst-tokenise`.

It would thus be very welcome to have a tool `hfst-realign` that would take such sequences and replace them with a single symbol pair `A:A`.

**Comment by mr-martian** [comment]
An idea for how to at least start this:

1. find non-branching sub-paths (that is, `A -> B -> ... -> C -> D` where `B, ..., C` have in-degree and out-degree 1)
2. apply `find_med_alingment` to each of those paths (same function used for `hfst-lexc --alignStrings`)

The sequences in step 2 would be split on flag diacritics to operate as described.

Would this be a reasonable approach or should more be done? If this is good I could probably code it later this week.
