### ISSUE TITLE
Different fst from the same source - mac vs linux

### ISSUE THREAD

**Issue by snomos** [hfst/hfst#406]
With the [following source file](https://gtsvn.uit.no/langtech/trunk/giella-shared/all_langs/src/morphology/url.lexc) compiled with the following command:

```
/usr/local/bin/hfst-lexc -v --format=openfst-tropical --Werror  --alignStrings -o url.hfst url.lexc
```

it behaves very differently on the mac vs on a Linux box. Here is a mac sample output:

```
$ echo http://www.samediggi.no/index.html | hfst-flookup -q url.hfst
http://www.samediggi.no/index.html	http://www.samediggi.no/index.html+URL
```

On Linux this same sequence results in the following:

```
$ echo http://www.samediggi.no/index.html | hfst-flookup -q url.hfst 
http://www.samediggi.no/index.html      http://www.samediggi.no/index.html+?    inf
```

It turns out that the fst's are hugely different, as seen by the attached diff between the mac and linux hfst's (diff of att files):
[url.mac.linux.unsorted.att.diff.zip](https://github.com/hfst/hfst/files/2427894/url.mac.linux.unsorted.att.diff.zip)

This bug affects at least the North Sámi nightly build maintained by @TinoDidriksen, most likely also other/all languages using the url analyser from the same source.

The bug is also registered [here](http://giellatekno.uit.no/bugzilla/show_bug.cgi?id=2509).

**Comment by eaxelson** [comment]
I get `http://www.samediggi.no/index.html+URL` both on Mac and Linux.

```
Linux 4.4.0-135-generic #161-Ubuntu SMP Mon Aug 27 10:45:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Darwin 14.5.0 Darwin Kernel Version 14.5.0: Sun Jun  4 21:40:08 PDT 2017; root:xnu-2782.70.3~1/RELEASE_X86_64 x86_64
```

**Comment by albbas** [comment]
I can confirm that, when compiling that specific file, I get the same result on my Linux box.

**Comment by eaxelson** [comment]
@snomos any progress on this issue?

**Comment by snomos** [comment]
Yes, this bug report turned out to be wrong. The bug was in our build system, not in the hfst code.
