### ISSUE TITLE
Require C++11 or even C++1y

### ISSUE THREAD

**Issue by TinoDidriksen** [hfst/hfst#407]
I only just noticed https://github.com/hfst/hfst/commit/318fdb58833c6cc022a988948a929a1cbc20f415 and I strongly object to it.

What platform is that desired for? I see that the `#ifdef` references `_MSC_VER` but that's wrong - the freely available version of Visual Studio supports much newer standards, even going back a few releases. And the new compilers can target older platforms.

For comparison, hfst-ospell, Apertium and CG-3 all require C++1y (pre-standard C++14).

**Comment by eaxelson** [comment]
Generating binary wheels for Mac requires OS X version 10.6 which doesn't support c++11. I don't remember exactly why 10.6 was required. I think pip didn't accept packages that used 10.7 and started to compile everything from scratch. Also, compiling binary wheels for python 2 for Windows requires using a c++ compiler that doesn't support c++11. (Although I'm not sure if we need to support python 2.) I couldn't find a solution to this problem so I decided just to write an alternative implementation for those places in code where c++11 features were used.

**Comment by TinoDidriksen** [comment]
Ergh. I think it's time to drop Python 2 support then. As https://pythonclock.org/ says, Python 2.7 will not be maintained past January 1st, 2020.

**Comment by eaxelson** [comment]
Ah, well I guess that solves the problem with python 2 support for Windows then. But the issue of generating binary wheels for Mac is still there. (OS X version 10.6 is required for all versions of python.)

**Comment by TinoDidriksen** [comment]
Google hits show other people using C++11 with Python3 on macOS. And it wouldn't make sense for C++11 to be a problem, given Python's API is C.

The only issue I can find is https://docs.brew.sh/C++-Standard-Libraries which only matters for installations upgraded through the years - fresh installs link against the C++11-capable libc++.
