### ISSUE TITLE
intersect rules in twolc file without composing with lexicon

### ISSUE THREAD

**Issue by reynoldsnlp** [hfst/hfst#428]
I am helping a student to write [a `twolc` grammar to convert Russian graphemes to phonemes](https://github.com/reynoldsnlp/rus_graph2phone). I can get my desired result **in `xfst`** with the following commands, but I can't find a way to achieve the same using the `hfst` command line tools.

```bash
printf "read-grammar g2p.twolc
compile
intersect
y
g2p-all
save-binary g2p.xfst
quit\n" | twolc

xfst -e "load stack < g2p.xfst" \
     -e "invert net" \
     -e "save stack g2p.lookup.xfst" \
     -stop
```

Specifically, I cannot find a way to get `hfst` to intersect the rules of a twolc grammar. The closest command-line utility I know of is `compose-intersect`, which also composes the twolc transducer with a lexicon transducer. However, I don't want to compose the twolc grammar with a lexicon.

Using the python library, I can intersect them using the following idiom:
```python
stream = hfst.HfstInputStream('path/to/g2p.hfst')
fsts = []
fst = None
if not stream.is_eof():
    fst = stream.read()
while not stream.is_eof():
    fsts.append(stream.read())
for fstrans in fsts:
    fst.intersect(fstrans)
# fst.invert()  # This gives `Segmentation fault: 11`, but maybe not necessary?
out = hfst.HfstOutputStream(filename='path/to/g2p.lookup.hfst')
out.write(fst)
out.flush()
out.close()
```

Maybe there is a better way to do it with `python`, but I can't find any way to do it with the command line tools. Is there a command-line utility that will intersect twolc rules, the same way the `intersect` works in the xfst twolc REPL?

**Comment by flammie** [comment]
Unless there has been an implementation to handle transducer archives in command line tools I don't know of, you'd do something like (untested):

```bash
hfst-split g2p.hfst --prefix g2prule --suffix .hfst
echo "?* ;" | hfst-regexp2fst -o g2pall.hfst
for fst in g2prule*.hfst ; do
  hfst-intersect $fst g2pall.hfst - o temp.hfst
  cp temp.hfst g2pall.hfst
done
```
i.e. hfst-split is a key to operate on multiautomata archives on command-line

**Comment by reynoldsnlp** [comment]
Thanks, @flammie! This appears to be working (with a couple minor corrections):

```bash
hfst-split g2p.hfst --prefix g2prule --extension .hfst
echo "?* ;" | hfst-regexp2fst -o g2pall.hfst
for fst in g2prule*.hfst ; do
  hfst-intersect $fst g2pall.hfst -o temp.hfst
  cp temp.hfst g2pall.hfst
done
rm g2prule*.hfst
```

**Comment by reynoldsnlp** [comment]
Nevermind, that output doesn't match the `xfst` output. However, the idea of `intersect`ing with the universal language made me think that I could `compose-intersect` with the universal language, and that seems to get the result I was looking for:

```bash
hfst-twolc -i g2p.twolc -o g2p.tmp.hfst
echo "creating base FST with universal language..."
echo "?* ;" | hfst-regexp2fst -o univ.hfst
echo "compose-intersecting twolc rules with universal FST..."
hfst-compose-intersect univ.hfst g2p.tmp.hfst > g2p.hfst
```

I don't understand why this works, and @flammie 's approach doesn't, but at least it works.
