### ISSUE TITLE
Limit the number of loops in a transducer?

### ISSUE THREAD

**Issue by gleec14** [hfst/hfst#433]
Is it possible to limit the number of loops in a transducer during compilation or in conversion to another transducer?
Is it possible to make a flat transducer without loops from a transducer that has loops?
@jonorthwash is curious about this too.

**Comment by flammie** [comment]
It's an interesting idea, tldr I would say that htere's no such conversion or way to unloop an automata so. It is perhaps doable to have a utility that traverses automaton and turns all cycle-introducing arcs into something that perhaps goes to a final sink state or so, but what it results in might or might not be useful. 

For lookups and generations the tools should already have some loop counting like so?

**Comment by jonorthwash** [comment]
> For lookups and generations the tools should already have some loop counting like so?

@flammie, `hfst-lookup` supports limiting the number of cycles, but does `hfst-proc`?  Alternatively, is there a straightforward way to use `hfst-lookup` in the Apertium pipeline?

Another related question: is there a good way you can think of to structure lexica in `lexc` to support the following generalisations?
* Noun+Noun compounds occur productively
* Noun+Verb compounds occur productively
* Verb+Noun compounds occur productively
* I believe Noun+Verb+Noun compounds are possible, but that's the extent of recursion possible.

(@gleec14, please correct any aspects of these generalisations that I got wrong.)

I guess maybe something could be done with flag diacritics, but I'd like to keep that as a last resort...

**Comment by flammie** [comment]
I guess only lexc solution would be to copy-paste the noun lexicon to like 1stNoun 2ndNoun and work with that. I think the typicallest solution would be an xfst or twol filter over the analysis side, something like `?* - $[+Noun ?* +Noun ?* +Noun]` I wouldn't even know how to work with flag diacritics for this. Hfst-lookup has some apertium output support but probably not input.

**Comment by jonorthwash** [comment]
Thanks, @flammie, this helps.

@gleec14, I think going with @flammie's typicallest solution is probably a good approach.  If you guys set up your transducer for prefixes as described on the Ling 073 wiki (it's the same methodology), then @mr-martian or I will help you figure out how to use the `twoc` file to remove paths in the transducer where you get anything besides N+N, N+V, V+N, and N+V+N (or whatever the right combinations are).
