### ISSUE TITLE
hfst-tokenise crashing on string with parenthesis

### ISSUE THREAD

**Issue by snomos** [hfst/hfst#443]
To reproduce, use the attached pmatch-processed fst, and do the following:

```
$ echo "daid dieđuid mielde ledje Agendas 3:16 (Normisjon) 10755 diŋgojeaddji jahkemolsumis." | hfst-tokenise -g tokeniser-gramcheck-gt-desc.pmhfst
"<daid>"
	"dat" Pron Dem Pl Acc <W:0.0>
	"dat" Pron Dem Pl Com Attr <W:0.0>
	"dat" Pron Dem Pl Gen <W:0.0>
	"dat" Pron Dem Pl Ill Attr <W:0.0>
: 
"<dieđuid>"
	"diehtu" N Sem/Prod-cogn_Txt Err/Orth Pl Acc <W:0.0>
	"diehtu" N Sem/Prod-cogn_Txt Err/Orth Pl Gen <W:0.0>
	"diehtu" N Sem/Prod-cogn_Txt Pl Acc <W:0.0>
	"diehtu" N Sem/Prod-cogn_Txt Pl Gen <W:0.0>
: 
"<mielde>"
	"de" Pcle <W:0.0> "<de>"
		"miel" Po <W:0.0> "<miel>"
	"mielde" Adv <W:0.0>
	"mielde" Po <W:0.0>
: 
"<ledje>"
	"leat" V IV Ind Prt Pl3 <W:0.0>
: 
"<Agendas>"
	"Agenda" N Prop Sem/Obj Sg Loc <W:0.0>
	"agenda" N Sem/Dummytag Sg Acc PxSg3 <W:0.0>
	"agenda" N Sem/Dummytag Sg Gen PxSg3 <W:0.0>
	"agenda" N Sem/Dummytag Sg Loc <W:0.0>
: 
"<3:16 >"
	"3:16" Num Sem/Time-clock Cmp/SplitR Err/SpaceCmp <W:0.0>
libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: basic_string
Abort trap: 6
```

[tokeniser-gramcheck-gt-desc.pmhfst.zip](https://github.com/hfst/hfst/files/3513109/tokeniser-gramcheck-gt-desc.pmhfst.zip)

We are about to release a grammar checker using hfst-tokenise as a central piece, so attention to this bug very soon would be greatly appreciated!

**Comment by snomos** [comment]
* macOS 10.14.6
* latest hfst (nightly build from TinoDidriksen, from about a week ago)

**Comment by unhammer** [comment]
Also crashes with the input `"1 ("` . On Linux, I see 

    terminate called after throwing an instance of 'std::out_of_range'
        what():  basic_string::substr: __pos (which is 18446744073709551615) > this->size() (which is 1)
    Aborted (core dumped)

**Comment by unhammer** [comment]
So this seems to be because of the possibility of a spaces-only (subreading) form – is there a badly placed backtracking symbol somewhere in those numerals? 

In any case, with f1dc19aa0493f7c3f21bb05fd0ef9cd0633205ee I get 
```
$ echo "1 (" | tools/src/hfst-tokenize -g tokeniser-gramcheck-gt-desc.pmhfst
"<1 >"
        "1-" Num Arab Sg Acc <W:0.0>
        "1-" Num Arab Sg Gen <W:0.0>
        "1-" Num Arab Sg Ill Attr <W:0.0>
        "1-" Num Arab Sg Loc Attr <W:0.0>
        "1-" Num Arab Sg Nom <W:0.0>
"<(>"
        "(" PUNCT LEFT <W:0.0>
:\n
```
and at least no crash.

**Comment by unhammer** [comment]
I'll close this; the weird Err/SpaceCmp probably belongs in giellatekno bugzilla.

**Comment by snomos** [comment]
Thanks for looking into this. Avoiding the crash was important, the Err/Space thing I have dealt with separately.
