### ISSUE TITLE
SWIG DeprecationWarning (fixed in SWIG 4.0.0)

### ISSUE THREAD

**Issue by reynoldsnlp** [hfst/hfst#446]
See issue here: https://github.com/swig/swig/issues/1621#issuecomment-527250111

> I'm using the `hfst` python package, which is compiled using `swig`, and I get the following `DeprecationWarning`:
> 
> ```
> DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
> ```
> 
> Looking at the SWIG-generated file...
> 
> ```python
> from sys import version_info
> if version_info >= (2, 6, 0):
>     def swig_import_helper():
>         from os.path import dirname
>         import imp
> ```

**Comment by TinoDidriksen** [comment]
I don't see how this is our problem. SWIG 4.0 is not broadly available yet. Builds use whichever SWIG we can get from the OS package manager, which is 2.0 and 3.0:
- http://mirror.centos.org/centos/7/os/x86_64/Packages/ 2.0
- http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/ 3.0
- https://packages.debian.org/search?keywords=swig 3.0
- https://packages.ubuntu.com/search?keywords=swig 3.0

macOS MacPorts has 4.0.

**Comment by reynoldsnlp** [comment]
@TinoDidriksen I was specifically thinking of the wheels provided [on PyPI](https://pypi.org/project/hfst/).

> For Windows and Mac OS X, we offer binary wheels on PyPI. Wheels are available for python versions 2.7, 3.4, 3.5 and 3.6. The wheels for Windows are 32-bit; they also require a 32-bit python to work correctly. Wheels for Mac are compiled as universal binaries that work both on 32- and 64-bit environments. OS X must be 10.6 or higher.

These could be rebuilt using SWIG 4.0 (and ideally add support for python 3.7 and 3.8). I would be happy to help with the macOS side of things. Do you know who has `hfst`'s credentials for the PyPI repo?
