### ISSUE TITLE
Can´t find symbols in compiled binaries on MacOS 10.12

### ISSUE THREAD

**Issue by shamuku** [hfst/hfst#451]
```
$ hfst-lexc huv.lexc -o huv.lexc.hfst
hfst-lexc: warning: Defaulting to OpenFst tropical type
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/labolingu/Downloads/hfst/bin/../lib/libhfst.52.dylib
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/labolingu/Downloads/hfst/bin/../lib/libhfst.52.dylib
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6
```
MacOS Version: 10.12.6 (16G29)

Using `hfst-latest`

**Comment by ftyers** [comment]
@TinoDidriksen could you check this out ?

**Comment by TinoDidriksen** [comment]
macOS 10.12 is ancient. Apple only supports last two releases, so currently 10.15 and 10.14. The build machine is kept up to date. From testing, the solution for now is to upgrade to at least 10.14.

**Comment by ftyers** [comment]
@TinoDidriksen is there a time when the HFST binaries supported 10.12 ? Could we potentially use an older version? -- The stuff we're doing lexc/twol hasn't really changed much in years.

**Comment by unhammer** [comment]
Travis runs 10.13.6 :(
