### ISSUE TITLE
Documentation link down

### ISSUE THREAD

**Issue by ftyers** [hfst/hfst#452]
KitWiki is not used any more, would be good to have links to the docs somewhere :)

**Comment by Trondtr** [comment]
... Documentation lint as a matter of fact still down :-( ... on behalf of incredibly many... Joke aside: This is actually a big problem (we don't have access to the documentation) with a small fix (correct the link) -- hopefully assuming that the documentation is not totally lost. So please try to fix this.

**Comment by TinoDidriksen** [comment]
I have no idea what was in the KitWiki, but does https://hfst.github.io/ + https://github.com/hfst/hfst/wiki cover it?

**Comment by Trondtr** [comment]
Probably, yes. The latter one resembles KitWiki, the former, well, perhaps also. If this indeed is our documentation we only need to update the links. I'll fix what I find.

**Comment by Trondtr** [comment]
No, I will (i.e.) can not:
git push
remote: Permission to hfst/hfst.git denied to Trondtr.
So: Please fix links (at the bottom of the README, and I think it was one more time) or, eventually give me access to check in.

**Comment by TinoDidriksen** [comment]
As for commit access, I can't add people to the hfst-dev team. @flammie ?

**Comment by eaxelson** [comment]
@Trondtr: I sent you an invitation.

**Comment by Trondtr** [comment]
Takk for invitasjon, eg er inne.

Trond

Trond Trosterud
Giellatekno, UiT Noregs arktiske universitet
trond.trosterud@uit.n
0047 776 44763

________________________________________
Lähettäjä: eaxelson <notifications@github.com>
Lähetetty: maanantai 11. tammikuuta 2021 11.42
Vastaanottaja: hfst/hfst
Kopio: Trond Trosterud; Mention
Aihe: Re: [hfst/hfst] Documentation link down (#452)

@Trondtr<https://github.com/Trondtr>: I sent you an invitation.
