### ISSUE TITLE
Decouple OpenFST

### ISSUE THREAD

**Issue by TinoDidriksen** [hfst/hfst#484]
Continuing from IRC discussion and email thread, I've tested that HFST builds and passes tests when using https://packages.debian.org/sid/libfst-dev instead of the bundled version.

Very few build and code adjustments needed:
* `#include "back-ends/openfst/src/include/fst/fstlib.h"` => `#include <fst/fstlib.h>`
* `#include "back-ends/openfst/src/include/fst/fst-decl.h"` => `#include <fst/fst-decl.h>`
* `$(top_builddir)/back-ends/openfst/src/lib/libfst.la` => `-lfst`
* Remove `-I${top_srcdir}/back-ends/openfst/src/include`
* Set `OPENFST_VERSION_1_5_4`

So it can fairly easily be put behind a `configure` flag.

Would also fix https://github.com/hfst/hfst/issues/358

**Comment by flammie** [comment]
I like the idea of just putting these behind config flag, it's definitely something I've seen other software do with bundled libraries when packaging for gentoo. Eventually if we test the whole stuff with whole giella infra and it seems to go well we can default to that too

**Comment by TinoDidriksen** [comment]
Thanks to @AmbientLighter, as of https://github.com/hfst/hfst/commit/734ae775580f36ad2bf798a96428c121014f2208 there is now configure flag `--with-openfst-upstream`.

I've verified that it builds and passes tests with Debian Sid's [libfst-dev 1.6.3-2](https://packages.debian.org/sid/libfst-dev), which is a good start, but even that version is 4 years old. I guess I'll have to package OpenFST in the nightly builds to make sure we're keeping up.

Not closing this issue yet - that should be done when the OpenFST code is removed from HFST.
