### ISSUE TITLE
automake subdir-objects warning

### ISSUE THREAD

**Issue by TinoDidriksen** [hfst/hfst#486]
This has been happening for ages, but nobody filed an issue for it:
````
libhfst/src/parsers/Makefile.am:42: warning: source file '$(CL_SRC)/CommandLine.cc' is in a subdirectory,
libhfst/src/parsers/Makefile.am:42: but option 'subdir-objects' is disabled
automake: warning: possible forward-incompatibility.
automake: At least a source file is in a subdirectory, but the 'subdir-objects'
automake: automake option hasn't been enabled.  For now, the corresponding output
automake: object file(s) will be placed in the top-level directory.  However,
automake: this behaviour will change in future Automake versions: they will
automake: unconditionally cause object files to be placed in the same subdirectory
automake: of the corresponding sources.
automake: You are advised to start using 'subdir-objects' option throughout your
automake: project, to avoid future incompatibilities.
...repeat for all the .cc files in subdir...
````

**Comment by TinoDidriksen** [comment]
Sorry, but that fix fails `make check`:
````
make[5]: Entering directory 'hfst/tools/src/hfst-tagger/src'
g++ -DHAVE_CONFIG_H -I. -I../../../.. -I../../../../libhfst/src  -I../../../../libhfst/src -Wno-sign-compare -Wno-unused-parameter  -DMAIN_TEST -Wno-deprecated -g -O2 -std=c++11 -MT ./build_model_src/FstBuilder-FstBuilder.o -MD -MP -MF ./build_model_src/.deps/FstBuilder-FstBuilder.Tpo -c -o ./build_model_src/FstBuilder-FstBuilder.o `test -f './build_model_src/FstBuilder.cc' || echo './'`./build_model_src/FstBuilder.cc
mv -f ./build_model_src/.deps/FstBuilder-FstBuilder.Tpo ./build_model_src/.deps/FstBuilder-FstBuilder.Po
make[5]: *** No rule to make target 'string_handling.o', needed by 'FstBuilder'.  Stop.
````

**Comment by flammie** [comment]
oof I have no idea of hfst-tagger unfortunately, seems odd

**Comment by flammie** [comment]
I sedded the makefile but it probably could be simplified. I noticed (from travis-ci) that actually subdir-objects only works on automake-1.16 or newer, quite :roll_eyes: from automake developers to deprecate functionality that is so new tbh... perhaps running these make checks isn't so important that users of outdated versions can do without though

**Comment by TinoDidriksen** [comment]
Curious that this failed on Travis' Bionic and still fails on Github's Bionic, because it works just fine on the nightly build's old distros with automake 1.15, including Xenial.

**Comment by flammie** [comment]
yeah I really thought subdir-objects had been workign just fine for years by now, though it seems from their release notes that 1.16 fixed a lot of corner cases. https://git.savannah.gnu.org/cgit/automake.git/tree/NEWS#n167
This probably only effects the new build instructions of the tagger thing that is not enabled by default?

it seems that github is also moving ubuntu-latest to 20.04 or something any day now so we wont have to wait too long to get builds back...
