### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by TinoDidriksen** [hfst/hfst#494]
A bunch of `libhfst/` files say `GNU Lesser General Public License as published by the Free Software Foundation; either version 3 of the License, or (at your option) any later version.` which is fine. But they're mixed with files licensed under `GNU General Public License as published by the Free Software Foundation, version 3 of the License.`

The lack of `any later version` on the GPLv3 files is odd, given the other files are LGPLv3+. And the fact that `hfst.hpp.in` is GPLv3-only means any library can't be LGPLv3+.

The folder https://github.com/hfst/hfst/tree/master/lgpl-release assumes all of `libhfst/` and `python/` are LGPLv3+, but that's currently not the case.

GPLv3-only files:
````
libhfst/src/hfst.hpp.in
libhfst/src/parsers/HfstTwolcDefs.h
libhfst/src/parsers/SfstCompiler.cc
libhfst/src/parsers/SfstCompiler.h
libhfst/src/parsers/TwolcCompiler.cc
libhfst/src/parsers/TwolcCompiler.h
libhfst/src/parsers/alphabet_src/Alphabet.cc
libhfst/src/parsers/alphabet_src/Alphabet.h
libhfst/src/parsers/commandline_src/CommandLine.h
libhfst/src/parsers/grammar_defs.h
libhfst/src/parsers/htwolcpre1-lexer.ll
libhfst/src/parsers/htwolcpre1-parser.yy
libhfst/src/parsers/htwolcpre2-lexer.ll
libhfst/src/parsers/htwolcpre2-parser.yy
libhfst/src/parsers/htwolcpre3-lexer.ll
libhfst/src/parsers/htwolcpre3-parser.yy
libhfst/src/parsers/io_src/InputReader.cc
libhfst/src/parsers/io_src/InputReader.h
libhfst/src/parsers/io_src/input_defs.h
libhfst/src/parsers/rule_src/ConflictResolvingLeftArrowRule.cc
libhfst/src/parsers/rule_src/ConflictResolvingLeftArrowRule.h
libhfst/src/parsers/rule_src/ConflictResolvingRightArrowRule.cc
libhfst/src/parsers/rule_src/ConflictResolvingRightArrowRule.h
libhfst/src/parsers/rule_src/LeftArrowRule.cc
libhfst/src/parsers/rule_src/LeftArrowRule.h
libhfst/src/parsers/rule_src/LeftArrowRuleContainer.cc
libhfst/src/parsers/rule_src/LeftArrowRuleContainer.h
libhfst/src/parsers/rule_src/LeftRestrictionArrowRule.cc
libhfst/src/parsers/rule_src/LeftRestrictionArrowRule.h
libhfst/src/parsers/rule_src/OtherSymbolTransducer.cc
libhfst/src/parsers/rule_src/OtherSymbolTransducer.h
libhfst/src/parsers/rule_src/RightArrowRule.cc
libhfst/src/parsers/rule_src/RightArrowRule.h
libhfst/src/parsers/rule_src/RightArrowRuleContainer.cc
libhfst/src/parsers/rule_src/RightArrowRuleContainer.h
libhfst/src/parsers/rule_src/Rule.cc
libhfst/src/parsers/rule_src/Rule.h
libhfst/src/parsers/rule_src/RuleContainer.cc
libhfst/src/parsers/rule_src/RuleContainer.h
libhfst/src/parsers/rule_src/TwolCGrammar.cc
libhfst/src/parsers/rule_src/TwolCGrammar.h
libhfst/src/parsers/string_src/string_manipulation.h
libhfst/src/parsers/variable_src/ConstContainerIterator.h
libhfst/src/parsers/variable_src/MatchedConstContainerIterator.h
libhfst/src/parsers/variable_src/MixedConstContainerIterator.h
libhfst/src/parsers/variable_src/RuleSymbolVector.cc
libhfst/src/parsers/variable_src/RuleSymbolVector.h
libhfst/src/parsers/variable_src/RuleVariables.cc
libhfst/src/parsers/variable_src/RuleVariables.h
libhfst/src/parsers/variable_src/RuleVariablesConstIterator.cc
libhfst/src/parsers/variable_src/RuleVariablesConstIterator.h
libhfst/src/parsers/variable_src/VariableBlock.h
libhfst/src/parsers/variable_src/VariableBlockContainer.h
libhfst/src/parsers/variable_src/VariableContainer.h
libhfst/src/parsers/variable_src/VariableContainerBase.h
libhfst/src/parsers/variable_src/VariableDefs.h
libhfst/src/parsers/variable_src/VariableValueIterator.h
libhfst/src/parsers/variable_src/VariableValues.cc
libhfst/src/parsers/variable_src/VariableValues.h
````

I need someone to confirm that the intention is that all of `libhfst/` is LGPLv3+ for Debian (cf. https://alioth-lists.debian.net/pipermail/debian-science-maintainers/2020-December/088040.html ). @mpsilfve is listed as author in the files I checked, but maybe @eaxelson or @flammie know?

**Comment by flammie** [comment]
I usually have my editor setup to copy paste GPLv3 licence without the later clause so it probably follows that files with such blurb are either originally mine or I've added the copyrights in mass with that statement. The LGPLv3 only version was added later by @mpsilfve. The original licence selection was I think based on the combination that can be done with foma's, sfst's and openfst's licence at the time, I think foma was GPLv2 only and openfst Apache and sfst probably GPLv2+? For this reason I think LGPL subset also doesn't link with foma or sfst?

**Comment by TinoDidriksen** [comment]
Looking at history, what actually happened was https://github.com/hfst/hfst/commit/9a1908804560a2792e1ec814cb14a0897983bfd0 - "Move most twolc code from tools/src to libhfst/src/parsers", which naturally kept their GPLv3 header.

That happened on 2017-03-13, but the `lgpl-release/` folder was created earlier on 2016-12-01. So I still need to know if the intention was that all those moved files should've been changed from GPLv3-only to LGPLv3+. I strongly assume so because anything else would invalidate the whole purpose of the lgpl-release, but I need someone to sign off on that.

**Comment by TinoDidriksen** [comment]
Debian Bullseye freeze is tomorrow, so if latest version has any chance of making it through migration for this Debian release, this issue must be settled today. Ping @eaxelson @mpsilfve.

**Comment by eaxelson** [comment]
> I usually have my editor setup to copy paste GPLv3 licence without the later clause so it probably follows that files with such blurb are either originally mine or I've added the copyrights in mass with that statement. The LGPLv3 only version was added later by @mpsilfve. The original licence selection was I think based on the combination that can be done with foma's, sfst's and openfst's licence at the time, I think foma was GPLv2 only and openfst Apache and sfst probably GPLv2+? For this reason I think LGPL subset also doesn't link with foma or sfst?

Yes, I think at the time the decision was made only OpenFST back-end was compatible to be linked to. I think we only needed a library package, so that's why the tools/src/ directory was left out.

**Comment by eaxelson** [comment]
> Looking at history, what actually happened was [9a19088](https://github.com/hfst/hfst/commit/9a1908804560a2792e1ec814cb14a0897983bfd0) - "Move most twolc code from tools/src to libhfst/src/parsers", which naturally kept their GPLv3 header.
> 
> That happened on 2017-03-13, but the `lgpl-release/` folder was created earlier on 2016-12-01. So I still need to know if the intention was that all those moved files should've been changed from GPLv3-only to LGPLv3+. I strongly assume so because anything else would invalidate the whole purpose of the lgpl-release, but I need someone to sign off on that.

I think also this is the case. I'll still have a look at the moved files.

**Comment by TinoDidriksen** [comment]
> I think also this is the case. I'll still have a look at the moved files.

Anything to sign off on? If so, I can update all the `libhfst/` files with the correct license and push a new release.

**Comment by eaxelson** [comment]
> > I think also this is the case. I'll still have a look at the moved files.
> 
> Anything to sign off on? If so, I can update all the `libhfst/` files with the correct license and push a new release.

Yes, you can update all files under `libhfst/` with the correct LGPLv3+ license.

**Comment by TinoDidriksen** [comment]
Updated all of HFST's files in libhfst/ to LGPLv3+. However, this revealed another quirk:

````
$ git grep -L 'GNU Lesser' libhfst/
libhfst/src/parsers/SfstAlphabet.cc
libhfst/src/parsers/SfstAlphabet.h
libhfst/src/parsers/SfstBasic.cc
libhfst/src/parsers/SfstBasic.h
libhfst/src/parsers/SfstUtf8.cc
libhfst/src/parsers/SfstUtf8.h
````

There are files in libhfst/ that are very clearly derivatives of SFST code and thus under SFST's license, which is GPLv2+. They were moved there in commit https://github.com/hfst/hfst/commit/3560d0b6b150a17ccea2cb19aa2385af75b142bc . We can upgrade those files to GPLv3+, but not side-step to LGPLv3+.

So unless HFST has some written agreement with Helmut Schmid to use LGPL for the bundled code, libhfst will have to either be GPLv3+ or remove SFST functionality.

So, this needs another round of examination @eaxelson.

**Comment by eaxelson** [comment]
> There are files in libhfst/ that are very clearly derivatives of SFST code and thus under SFST's license, which is GPLv2+. They were moved there in commit [3560d0b](https://github.com/hfst/hfst/commit/3560d0b6b150a17ccea2cb19aa2385af75b142bc) . We can upgrade those files to GPLv3+, but not side-step to LGPLv3+.
> 
> So unless HFST has some written agreement with Helmut Schmid to use LGPL for the bundled code, libhfst will have to either be GPLv3+ or remove SFST functionality.

We have an agreement with Helmut Schmid that the derivatives of SFST code related to parsing SFST-PL (SFST Programming Language) can be included in the LGPLv3+ version of HFST. That is, the Sfst* and sfst-* files in `libhfst/src/parsers/`. I confirmed this with him via email.

**Comment by TinoDidriksen** [comment]
Excellent. That should cover it then. I'll make a note of this in the files, to avoid future questions.
