### ISSUE TITLE
hfst-tokenise --visl and --giella-cg tokenises lemma wrongly

### ISSUE THREAD

**Issue by snomos** [hfst/hfst#497]
Cf the following examples from [lang-lut](https://github.com/giellalt/lang-lut):

```sh
echo 'bək̓ʷ'| hfst-tokenise -g -W -m tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst 
"<bək̓ʷ>"
	"bə"k̓ʷ Adv Tot
:\n
echo 'bək̓ʷ'| hfst-tokenise -L -W -m tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst 
"<bək̓ʷ>"
	"bə"k̓ʷ Adv Tot
```

Other output modes do not have this issue:

```sh
echo 'bək̓ʷ'| hfst-tokenise -W -m tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst 
bək̓ʷ

echo 'bək̓ʷ'| hfst-tokenise -x -W -m tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst 
bək̓ʷ	bək̓ʷ Adv Tot

echo 'bək̓ʷ'| hfst-tokenise -c -W -m tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst 
"<bək̓ʷ>"
	"bək̓ʷ" Adv Tot

echo 'bək̓ʷ'| hfst-tokenise -C -W -m tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst 
1	bək̓ʷ	_	_	_	_	_	_	_	bək̓ʷ Adv Tot
echo 'bək̓ʷ'| hfst-tokenise -f -W -m tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst 
bək̓ʷ	_	_	Tot	_
```

It seems to be triggered by the `U+02B7` (MODIFIER LETTER SMALL W), as other types of input is tokenised just fine:

```sh
echo 'ƛ̕aƛ̕ac̓apəd'| hfst-tokenise -g -W -m tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst 
"<ƛ̕aƛ̕ac̓apəd>"
	"ƛ̕aƛ̕ac̓apəd" N Sg Nom
:\n
```

Another example word displaying the problem:

```sh
echo 'sčətxʷəd'| hfst-tokenise -g -W -m tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst 
"<sčətxʷəd>"
	"sčət"xʷ"əd" N Sg Nom
:\n
```

@unhammer, could you have a look?

**Comment by unhammer** [comment]
Related:
* https://github.com/hfst/hfst/issues/367 
* https://github.com/hfst/hfst/issues/440
* https://github.com/hfst/hfst/issues/439

**Comment by unhammer** [comment]
Other output modes don't have the issue since they don't have the feature – they insert `"` around the lemma.

The issue comes up because HFST doesn't have any way of saying that an arc symbol is a tag or part of a lemma. The first idea we tried was to say that all tags were exactly the multichar_symbols (technically, those that take up >1 utf-8 codepoint), but that failed when some transducers had composed chars on single arc. So we started using ICU's character-break iterator to check if the arc was longer than what ICU calls a character.

However, `k̓ʷ` is a UnicodeString of length 3 but the first character boundary is at position (`k̓`), so it gets treated as a tag. 

I haven't tested, but I think the two most reasonable options are either
- turn `k̓ʷ` into two arcs in the FST (they're not composed in input, so why keep them composed in the FST?)
- add special casing to [is_cg_tag](https://github.com/hfst/hfst/blob/master/libhfst/src/implementations/optimized-lookup/pmatch_tokenize.cc#L226-L236) to skip modifier letters

What do you think?

**Comment by Trondtr** [comment]
I run into the same problem, here, for vro:

e kunst | hfst-tokenise -cg -m tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst 
"<kunst>"
	"kuns"t́ N Err/Orth-no-pal Sg Nom <W:0.0>
	"kuns"t́ N Sg Nom <W:0.0>

as compared to

e kunst | huvro
kunst	kunst́+N+Err/Orth-no-pal+Sg+Nom	0,000000
kunst	kunst́+N+Sg+Nom	0,000000

There is only one t + U+0301, there is no precomposed palatal t, and the composed one is declared in root.lexc, in phonology.twolc, and in the pmscript (but not in the grammarchecker pmscript, come to look at it).

Thus, Kevin's last point (length 3) seems irrelevant to my problem

**Comment by Trondtr** [comment]
The same problem goes the opposite direction as well (analysing t + 0301):

uit-mac-443:lang-vro ttr000$ e kunst́ |hfst-tokenise -cg tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst 
"<kunst́>"
	"kunst́" ?
:\n
uit-mac-443:lang-vro ttr000$ e kunst́ |huvro
kunst́	kunst́+N+Sg+Nom	0,000000

**Comment by unhammer** [comment]
I think @Trondtr 's problem is unrelated to this issue. With newest lang-vro I get:

```
$ echo kunst́ |hfst-tokenise -g -m tokeniser-disamb-gt-desc.pmhfst
"<kunst́>"
        "kunst́" N Sg Nom <W:0.0>
:\n
```

(btw, the options to hfst-tokenise should probably be `-g -m`

**Comment by Trondtr** [comment]
I am not able to repeate this:

**Comment by Trondtr** [comment]
e kunst|hfst-tokenise -g -m tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst
"<kunst>"
	"kuns"t́ N Err/Orth-no-pal Sg Nom <W:0.0>
	"kuns"t́ N Sg Nom <W:0.0>

**Comment by Trondtr** [comment]
And yes, it was the newest lang-vro:

uit-mac-443:lang-vro ttr000$ git pull
Already up to date.

**Comment by Trondtr** [comment]
Come to think of it, kevin runs Linux and I mac. Could that be a factor?

**Comment by carges** [comment]
with the newest lang-vro I get the same problem as Trond:
````
echo kunst |hfst-tokenise -g -m tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst 
"<kunst>"
	"kuns"t́ N Err/Orth-no-pal Sg Nom <W:0.0>
	"kuns"t́ N Sg Nom <W:0.0>
:\n
````

**Comment by snomos** [comment]
> I haven't tested, but I think the two most reasonable options are either
> 
> * turn `k̓ʷ` into two arcs in the FST (they're not composed in input, so why keep them composed in the FST?)
> * add special casing to [is_cg_tag](https://github.com/hfst/hfst/blob/master/libhfst/src/implementations/optimized-lookup/pmatch_tokenize.cc#L226-L236) to skip modifier letters
> 
> What do you think?

I agree, with priority to the first option. I would probably implement both, thinking that the second option is a reasonable fallback strategy. `hfst-tokenise` should probably give a warning on `stderr` when input requiring the second option is encountered.

**Comment by snomos** [comment]
> ```sh
> echo kunst | hfst-tokenise -cg -m tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst
> ""
> "kuns"t́ N Err/Orth-no-pal Sg Nom <W:0.0>
> "kuns"t́ N Sg Nom <W:0.0>
> ```
> as compared to
> 
> ```sh
> echo kunst | huvro
> kunst kunst́+N+Err/Orth-no-pal+Sg+Nom 0,000000
> kunst kunst́+N+Sg+Nom 0,000000
> ```
> 
> There is only one t + U+0301, there is no precomposed palatal t, and the composed one is declared in root.lexc, in phonology.twolc, and in the pmscript (but not in the grammarchecker pmscript, come to look at it).

I think that Kevin's point is that the lexc/twolc code should NOT declare the composed char as a multichar symbol. It should not have any impact on the fst performance.

If it makes twolc rules simpler, one can declare them as multichars for the purpose of simplifying things, but then ensure that they are later in the fst compilation process re-expanded to a sequence of two symbols, to make sure that all tools are accepting input text properly.

**Comment by Trondtr** [comment]
For lexc it is easy: I comment them out as multichar, and test.
for twolc, the whole alphabet must be declared, but I guess that will then mean 
t d f v h ́ 
rather than
t d f v h t́ d́ f́ v́ h́
as today

**Comment by TinoDidriksen** [comment]
With the nightly vro tokenizer built on Linux (Debian Sid locale C.UTF-8), I get the same output on both Linux and macOS for both `kunst` and `kunst́`. And this holds for vro built on my Mac Mini (locale en_US.UTF-8) just now.

I cannot reproduce output `"kuns"t́` for any combination.

**Comment by Trondtr** [comment]
Thanks to Sjur the interpreter :-) I now commented out the composed characters from twolc and lexc, and then it worked. I should probably do the same with the other composed characters, but I'll perhaps wait for a test case before I do. 

I now check in the new twolc and lexc files, and leave the 3-arch to you.

Tino: Thanks for the comment, but I do not understand your result, as both Chiara and I get (in my case: got) the flawed version (as indicated) on our macs. Thanks for your effort. We need a working pipeline now, and I will check in files according to Sjur's advice, but will leave comments in the code and follow the behaviour of the fsts.

**Comment by unhammer** [comment]
@Trondtr @carges   are you running the newest versions of HFST?

**Comment by unhammer** [comment]
> hfst-tokenise should probably give a warning on stderr when input requiring the second option is encountered

Give a warning whenever we find a multichar symbol consisting of just character + modifier (as in k̓ʷ )?

**Comment by snomos** [comment]
> > hfst-tokenise should probably give a warning on stderr when input requiring the second option is encountered
> 
> Give a warning whenever we find a multichar symbol consisting of just character + modifier (as in k̓ʷ )?

Give a warning whenever a multichar symbol contains a modifier letter (or any similar, suspicious class of letters). The warning should advice the developer to declare such multichars as individual symbols instead, and list the multichar symbol(s) in question.

**Comment by flammie** [comment]
I might be wrong but maybe the "kuns"t́  tokenisation can both come from old version of hfst *or* if ICU is turned off? 

I kind of liked the logic of parsing multichar_symbols as analysis symbols, it used to match typical use of lexc et al, but one alternative / workaround that we used earlier or maybe is used in hfst-lookup still–is that a very short list of symbols in start and/or end of a multichar symbol means that it is an analysis symbol, i.e. `[-+<>() ]`.
