### ISSUE TITLE
Require ICU

### ISSUE THREAD

**Issue by TinoDidriksen** [hfst/hfst#501]
As per https://github.com/giellalt/template-lang-und/issues/14 and many other issues that were fixed "only when using ICU", I think it's time HFST drops the non-ICU code paths and configure options. ICU is the way forward - so let's formally require it.

Ping @eaxelson , @Traubert , @flammie , @unhammer - any objections?

**Comment by unhammer** [comment]
Was just bitten by it myself, had typed `./configure` without enabling icu and got myself confused for half an hour

**Comment by flammie** [comment]
should work fine with current packaging approaches and the installation coverage of icu in most popular base systems.

**Comment by Trondtr** [comment]
For me, working (increasingly) with languages far away from the a-z repertoire, progress on this issue would **really** be appreciated. Thanks to Tino for bringing it up.
