### ISSUE TITLE
hfst-dev Python package does not support Windows

### ISSUE THREAD

**Issue by mikahama** [hfst/hfst#559]
I changed my Python library [UralicNLP](https://github.com/mikahama/uralicNLP) recently to use hfst-dev instead of hfst as recommended by @eaxelson. This was mainly needed because hfst hasn't been precompiled for Python 3.8. However, hfst-dev has only been precompiled for Linux and Mac.

This means that nobody can install hfst-dev on Windows at all, which also means that my UralicNLP won't work on Windows now. Would it be possible to upload precompiled wheels for Windows as well? There isn't even a source package so pip cannot try to compile from the source code.

**Comment by MatsRooth** [comment]
You could try it with Windows Subsystems for Linux under Windows.

**Comment by mikahama** [comment]
The default Python version in many linux distros is already too recent, so it will not work either. Either hfst-dev or hfst should be precompiled for all new Python versions, on all three operating systems and also for arm64 and amd64.

**Comment by mikahama** [comment]
We ended up developing [pyhfst](https://github.com/Rootroo-ltd/pyhfst) which is a pure Python implementation of HFST optimized lookup. It can be installed on all operating systems and Python versions.
