### ISSUE TITLE
3.16 Unicode handler

### ISSUE THREAD

**Issue by jengelh** [hfst/hfst#563]
In 3.16, ICU became mandatory:

```
AC_CHECK_ICU([50], [AC_DEFINE([USE_ICU_UNICODE], 1, 
                    [if using icu for unicode string handling])],
             [AC_MSG_FAILURE([ICU-50 or newer is required])])
```

given that, is it still worthwhile to offer `--with-unicode-handler=glib`? (Else, ICU should be optional.)

**Comment by TinoDidriksen** [comment]
Nope, that should be removed, along with all the dependent code behind `#ifdef`
