### ISSUE TITLE
Build fails on Arch Linux with missing xre_lex.cc

### ISSUE THREAD

**Issue by joveian** [hfst/hfst#572]
I am following [archlinux-apertium-all-dev.sh](https://apertium.projectjj.com/archlinux-apertium-all-dev.sh) and find that the hfst build is failing with xre_lex.cc not found.  The file does not exist and neither generate-cc-files.sh nor make xre_lex.cc generate the file (but with no error message).  Reverting the last commit, that is removing ([yywrap]) after AC_PROG_LEX in configure.ac allows the build to succeed (with no test FAILs).

**Comment by TinoDidriksen** [comment]
It failed to build on Debian/Ubuntu as well, but I didn't notice. Builds for me with `noyywrap` instead of `yywrap`, and I hope adding a parameter won't break on older supported distros that don't have autoconf 2.70 yet.
