### ISSUE TITLE
win32 executables download link gives 404

### ISSUE THREAD

**Issue by electric-coder** [hfst/hfst#577]
If we try downloading the win32 executables at the HFST page https://hfst.github.io/downloads/index.html we get a 404 not found page.

> HFST Download Page
>
> via Apertium as Debian packages for Linux, `[win32 executables](http://apertium.projectjj.com/win32/nightly/) for Windows](http://apertium.projectjj.com/win32)`

**Comment by TinoDidriksen** [comment]
I forgot to make a symlink and/or update docs. New URL is https://apertium.projectjj.com/windows/

**Comment by electric-coder** [comment]
@TinoDidriksen I would suggest updated the docs with the new link because that's where most users are likely to search.
