### ISSUE TITLE
mismatched new[] and delete in hfst3 header parsing

### ISSUE THREAD

**Issue by hfst-importer** [hfst/hfst#62]
Valgrind reports on proc functionality tests:

==17600== Mismatched free() / delete / delete []
==17600==    at 0x4C27FFF: operator delete(void*) (vg_replace_malloc.c:387)
==17600==    by 0x4134C6: handle_hfst3_header(std::istream&) (hfst-proc.cc:66)
==17600==    by 0x414080: main (hfst-proc.cc:356)
==17600==  Address 0x96cc5f0 is 0 bytes inside a block of size 104 alloc'd
==17600==    at 0x4C28658: operator new[](unsigned long) (vg_replace_malloc.c:305)
==17600==    by 0x413316: handle_hfst3_header(std::istream&) (hfst-proc.cc:51)
==17600==    by 0x414080: main (hfst-proc.cc:356)
==17600== 

Reported by: flammie

**Comment by eaxelson** [comment]
Fixed in revision 966a895.
